{
 "title": "Uptime Dashboard",
 "description": "The uptime dashboard displays data about the hosts, high availability vms and all vms uptime and downtime.",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name AS __text , datacenter_id AS __value FROM v4_3_latest_configuration_datacenters"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT cluster_name AS __text, cluster_id AS __value FROM v4_3_configuration_history_clusters WHERE datacenter_id = '$datacenter_id'"
   },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
   "content": "\n###### This dashboard displays uptime and downtime data for the hosts, high availability virtual machines and all virtual machines in the selected cluster.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Unplanned Downtime (BR7A)",
   "type": "gauge",
   "description": "The average unplanned downtime per cluster.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "-- BR7A - This query returns the\n-- average planned and unplanned downtime,\n-- average uptime and total time per cluster.\n\n-- unplanned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( unplanned_downtime_mins ) / AVG ( total ) AS unplanned_downtime\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM \n                ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_hosts\n                ON \n                    (\n                        v4_3_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_clusters.cluster_id =\n                        v4_3_configuration_history_hosts.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_hosts.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest hosts configuration\n            AND v4_3_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_hosts AS b\n                        GROUP BY b.host_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_hosts.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Planned Downtime (BR7A)",
   "type": "gauge",
   "description": "The average planned downtime per cluster.",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "-- BR7A - This query returns the\n-- average planned and unplanned downtime,\n-- average uptime and total time per cluster.\n\n-- planned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( planned_downtime_mins ) / AVG ( total ) AS planned_downtime\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 2\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM \n                ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_hosts\n                ON \n                    (\n                        v4_3_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_clusters.cluster_id =\n                        v4_3_configuration_history_hosts.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_hosts.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest hosts configuration\n            AND v4_3_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_hosts AS b\n                        GROUP BY b.host_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_hosts.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Cluster (BR7A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, average uptime and total time per cluster.",
   "gridPos": { "h": 4, "w": 14, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "-- BR7A - This query returns the\n-- average planned and unplanned downtime,\n-- average uptime and total time per cluster.\n\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( uptime_mins ) AS uptime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 2\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_hosts\n                ON \n                    (\n                        v4_3_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_clusters.cluster_id =\n                        v4_3_configuration_history_hosts.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_hosts.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest hosts configuration\n            AND v4_3_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_hosts AS b\n                        GROUP BY b.host_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_hosts.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            hourly_daily.host_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Host (BR7A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, and total time for each host per cluster.",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "-- BR7A - This query returns the\n-- average planned and unplanned downtime,\n-- average uptime and total time per cluster.\n\nSELECT\n    name AS cluster_name,\n    host_name,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_hosts.host_name,\n            hourly_daily.host_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 2\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.host_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_hosts\n                ON \n                    (\n                        v4_3_configuration_history_hosts.host_id =\n                        hourly_daily.host_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_clusters.cluster_id =\n                        v4_3_configuration_history_hosts.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_hosts.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest hosts configuration\n            AND v4_3_configuration_history_hosts.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_hosts AS b\n                        GROUP BY b.host_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_hosts.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_hosts.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_hosts.host_name,\n            hourly_daily.host_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date, host_name\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "High Availability Virtual Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Unplanned Downtime (BR14A)",
   "type": "gauge",
   "description": "The average unplanned downtime per cluster and virtual machine server.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\n-- unplanned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    AVG ( unplanned_downtime_mins ) / AVG ( total ) AS unplanned_downtime\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n            AND v4_3_configuration_history_vms.vm_type = 1\n            -- Here we get only vms that are marked as \"high availability\"\n            AND high_availability = TRUE\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Planned Downtime (BR14A)",
   "type": "gauge",
   "description": "The average planned downtime per cluster and virtual machine server.",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\n-- planned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    AVG ( planned_downtime_mins ) / AVG ( total ) AS planned_downtime\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n            AND v4_3_configuration_history_vms.vm_type = 1\n            -- Here we get only vms that are marked as \"high availability\"\n            AND high_availability = TRUE\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Cluster (BR14A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, and total time per cluster and virtual machine server.",
   "gridPos": { "h": 5, "w": 14, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n            AND v4_3_configuration_history_vms.vm_type = 1\n            -- Here we get only vms that are marked as \"high availability\"\n            AND high_availability = TRUE\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Virtual Machine (BR14A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, and total time for each high availability virtual machine per cluster and virtual machine server.",
   "gridPos": { "h": 5, "w": 14, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    vm_name,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_name,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n            AND v4_3_configuration_history_vms.vm_type = 1\n            -- Here we get only vms that are marked as \"high availability\"\n            AND high_availability = TRUE\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_name,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date, vm_name \nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  { "title": "All Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Unplanned Downtime (BR14A)",
   "type": "gauge",
   "description": "The average unplanned downtime per cluster and virtual machine server.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\n-- unplanned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( unplanned_downtime_mins ) / AVG ( total ) AS unplanned_downtime_mins\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN v4_3_statistics_vms_resources_usage_hourly.vm_status = 3\n                            THEN COALESCE ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN v4_3_statistics_vms_resources_usage_hourly.vm_status = 1\n                            THEN COALESCE ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status ) AS total\n        FROM \n            v4_3_statistics_vms_resources_usage_hourly\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        v4_3_statistics_vms_resources_usage_hourly.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Planned Downtime  (BR14A)",
   "type": "gauge",
   "description": "The average planned downtime per cluster and virtual machine server.",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\n-- planned downtime\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( planned_downtime_mins ) / AVG ( total )  AS planned_downtime_mins\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN v4_3_statistics_vms_resources_usage_hourly.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN v4_3_statistics_vms_resources_usage_hourly.vm_status = 1\n                            THEN COALESCE ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( v4_3_statistics_vms_resources_usage_hourly.minutes_in_status ) AS total\n        FROM \n            v4_3_statistics_vms_resources_usage_hourly\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        v4_3_statistics_vms_resources_usage_hourly.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Cluster (BR14A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, and total time per cluster.",
   "gridPos": { "h": 4, "w": 14, "x": 8, "y": 26 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster.\n\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    delete_date,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n            AND v4_3_configuration_history_vms.vm_type = 1\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  },
  {
   "title": "Downtime by Virtual Machine (BR14A)",
   "type": "table",
   "description": "The average planned and unplanned downtime, and total time for each virtual machine per cluster.",
   "gridPos": { "h": 5, "w": 14, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "-- BR14A - This query returns the\n-- average unplanned downtime, uptime\n-- and total time per cluster and vm server.\n\nSELECT\n    cluster_id,\n    name AS cluster_name,\n    vm_name,\n    CAST (high_availability AS varchar) AS high_availability,\n    AVG ( unplanned_downtime_mins ) AS unplanned_downtime_mins,\n    AVG ( planned_downtime_mins ) AS planned_downtime_mins,\n    AVG ( total ) AS total\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name AS name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            v4_3_configuration_history_vms.vm_name,\n            high_availability,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 3\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS unplanned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status IN ( 2, 0 )\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS planned_downtime_mins,\n            SUM \n                (\n                    CASE\n                        WHEN hourly_daily.vm_status = 1\n                            THEN COALESCE ( hourly_daily.minutes_in_status, 0 )\n                        ELSE 0\n                    END\n                ) AS uptime_mins,\n            SUM ( hourly_daily.minutes_in_status ) AS total\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n            INNER JOIN v4_3_configuration_history_vms\n                ON \n                    (\n                        v4_3_configuration_history_vms.vm_id =\n                        hourly_daily.vm_id\n                    )\n            INNER JOIN v4_3_configuration_history_clusters\n                ON \n                    (\n                        v4_3_configuration_history_vms.cluster_id =\n                        v4_3_configuration_history_clusters.cluster_id\n                    )\n        WHERE\n            -- Here we filter by the datacenter chosen by the user\n            v4_3_configuration_history_vms.cluster_id in ($cluster_id)\n            -- Here we get only vms of type \"server\"\n         -- AND v4_3_configuration_history_vms.vm_type = 1\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest clusters configuration\n            AND v4_3_configuration_history_clusters.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_clusters AS a\n                        GROUP BY a.cluster_id\n                    )\n            -- Here we get the latest vms configuration\n            AND v4_3_configuration_history_vms.history_id \n                IN \n                    (\n                        SELECT MAX ( b.history_id )\n                        FROM v4_3_configuration_history_vms AS b\n                        GROUP BY b.vm_id\n                    )\n            -- This will determine if deleted hosts will be included in the report,\n            -- according to the user selection for \"show_deleted\" parameter\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_3_configuration_history_vms.delete_date isnull\n                END\n        GROUP BY\n            v4_3_configuration_history_vms.cluster_id,\n            v4_3_configuration_history_clusters.cluster_name,\n            v4_3_configuration_history_clusters.delete_date,\n            v4_3_configuration_history_vms.vm_id,\n            v4_3_configuration_history_vms.vm_name,\n            high_availability\n    ) AS sub_query\nGROUP BY cluster_id, name, delete_date, vm_name, high_availability\nORDER BY\n    (\n        CASE\n            WHEN delete_date IS NULL\n                THEN 0\n            ELSE 1\n        END\n    ) ASC,\n    CAST ( AVG ( uptime_mins ) AS float ) / CAST ( AVG ( total ) AS float ) DESC"
    }
   ]
  }
 ]
}