{
 "title": "System Overview Dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datacenter_name",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name FROM v4_4_configuration_history_datacenters "
   },
   {
    "name": "datacenter_id",
    "query": "SELECT DISTINCT datacenter_id FROM v4_4_configuration_history_datacenters WHERE datacenter_name='$datacenter_name'"
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": "SELECT cluster_name FROM v4_4_configuration_history_clusters WHERE datacenter_id = '$datacenter_id'"
   },
   {
    "name": "cluster_id",
    "query": "SELECT cluster_id FROM v4_4_configuration_history_clusters WHERE cluster_name = '$cluster_name'"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "SELECT host_name FROM v4_4_configuration_history_hosts WHERE cluster_id IN ('$cluster_id')"
   },
   {
    "name": "host_id",
    "query": "SELECT host_id FROM v4_4_configuration_history_hosts WHERE host_name = '$hostname'"
   },
   { "name": "show_deleted", "label": "Show deleted entities?", "query": "Yes,No" }
  ]
 },
 "panels": [
  { "title": "Executive Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Virtual Machines by OS (BR18)",
   "type": "table",
   "description": "The report contains comparative measurements number of running virtual machines and OS usage in for a selected cluster within the requested period.",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    COALESCE (\n        os_type,\n        'RHEL'\n    )\n    AS os_type,\n    AVG(vm_count),\n    MAX(vm_count),\n    MIN(vm_count)\nFROM (\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_samples\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"is_deleted\" parameter\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        history_datetime\n\nUNION ALL\n\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_hourly\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_hourly.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_hourly.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_hourly.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        History_datetime\n\nUNION ALL\n\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_daily\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_daily.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_daily.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_daily.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        history_datetime\n)\nAS all_query\nGROUP BY os_type\nORDER BY os_type"
    }
   ]
  },
  {
   "title": "Host OS Break Down (BR22)",
   "type": "table",
   "description": "This report contains a table and a chart displaying the number of hosts for each OS version for a selected cluster within a requested period.",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' ) AS os_type,\n    COUNT ( DISTINCT v4_4_configuration_history_hosts.host_id ) AS host_count\nFROM  v4_4_statistics_hosts_resources_usage_hourly AS stats_hosts\n    INNER JOIN v4_4_configuration_history_hosts\n        ON (\n            v4_4_configuration_history_hosts.history_id =\n            stats_hosts.host_configuration_version\n        )\n    INNER JOIN v4_4_configuration_history_hosts a\n        ON (\n            a.host_id =\n            stats_hosts.host_id\n        )\nWHERE\n    v4_4_configuration_history_hosts.cluster_id IN (\n        SELECT v4_4_configuration_history_clusters.cluster_id\n        FROM v4_4_configuration_history_clusters\n        WHERE\n            v4_4_configuration_history_clusters.datacenter_id = '$datacenter_id'\n    )\n    -- Here we filter by the cluster chosen by the user\n    AND v4_4_configuration_history_hosts.cluster_id IN ( '$cluster_id' )\n    AND history_datetime >= $__timeFrom()\n    AND history_datetime < $__timeTo()\n    -- Here we get the latest host configurations\n    AND a.history_id IN (\n        SELECT MAX ( b.history_id )\n        FROM v4_4_configuration_history_hosts b\n        GROUP BY b.host_id\n    )\n    AND\n        CASE\n            WHEN '$show_deleted' = 'No'\n                THEN a.delete_date IS NULL\n            ELSE\n                a.delete_date IS NULL\n                OR\n                a.delete_date IS NOT NULL\n        END\nGROUP BY\n    COALESCE ( v4_4_configuration_history_hosts.host_os, 'Unknown' )"
    }
   ]
  },
  {
   "title": "Active Virtual Machines by OS (BR18)",
   "type": "graph",
   "description": "The report contains comparative measurements of number of running virtual machines and OS usage for a selected cluster within the requested period.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    $__time(time),\n    COALESCE (\n        os_type,\n        'RHEL'\n    )\n    AS os_type,\n    vm_count\nFROM (\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_samples\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"is_deleted\" parameter\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        History_datetime\n\nUNION ALL\n\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_hourly\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_hourly.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_hourly.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_hourly.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"is_deleted\" parameter\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        History_datetime\n\nUNION ALL\n\n    SELECT DISTINCT\n        CASE\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER (COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE( enum_os_type.value,'Other OS' ) ) LIKE '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END\n        AS os_type,\n        history_datetime AS time,\n        COUNT ( DISTINCT v4_4_configuration_history_vms.vm_id ) AS vm_count\n    FROM v4_4_statistics_vms_resources_usage_daily\n        INNER JOIN v4_4_configuration_history_vms\n            ON (\n                v4_4_configuration_history_vms.history_id =\n                v4_4_statistics_vms_resources_usage_daily.vm_configuration_version\n            )\n        INNER JOIN enum_translator enum_os_type\n            ON (\n                enum_os_type.enum_key =\n                v4_4_configuration_history_vms.operating_system\n                AND enum_os_type.enum_type = 'OS_TYPE'\n                AND language_code = 'en_US'\n            )\n        INNER JOIN v4_4_configuration_history_vms latest_config\n            ON (\n                latest_config.vm_id =\n                v4_4_statistics_vms_resources_usage_daily.vm_id\n            )\n    WHERE\n        -- Here we filter only the vms that are in active status\n        v4_4_statistics_vms_resources_usage_daily.vm_status = 1\n        -- Filter vms list according to the datacenter that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN\n            (\n                SELECT cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE datacenter_id = '$datacenter_id'\n            )\n        -- Filter vms list according to the cluster that was chosen by the user\n        AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n        -- Here we get the vm latest configuration\n        AND latest_config.history_id IN\n            (\n                SELECT MAX ( b.history_id )\n                FROM v4_4_configuration_history_vms b\n                GROUP BY b.vm_id\n            )\n       AND history_datetime >= $__timeFrom()\n       AND history_datetime < $__timeTo()\n       AND\n            -- This will determine where deleted entities will be included in the report,\n            -- according to the user selection for \"is_deleted\" parameter\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN latest_config.delete_date IS NULL\n                ELSE\n                    latest_config.delete_date IS NULL\n                    OR\n                    latest_config.delete_date IS NOT NULL\n            END\n    GROUP BY\n        CASE\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) = 'OTHER OS'\n                THEN 'Other OS'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%WINDOWS%'\n                THEN 'Windows'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RHEL%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'RED HAT%'\n                THEN 'RHEL'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'OTHER L%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like 'LINUX'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%UBUNTU%'\n                THEN 'Other Linux'\n            WHEN UPPER ( COALESCE ( enum_os_type.value,'Other OS' ) ) like '%SUSE%'\n                THEN 'Other Linux'\n            ELSE 'Other OS'\n        END,\n        history_datetime\n)\nAS all_query\nORDER BY os_type"
    }
   ]
  },
  {
   "title": "Host OS Break Down Over Time (BR22)",
   "type": "graph",
   "description": "This report contains a table and a chart displaying the number of hosts for each OS version for a selected cluster within a requested period.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    $__time(history_datetime),\n    COALESCE ( os_type, MAX ( os_type ) over (partition by 1), '' ) AS os_type,\n    host_count\nFROM (\n    SELECT\n        history_datetime,\n        COALESCE (\n            v4_4_configuration_history_hosts.host_os,\n            'Unknown'\n        )\n        AS os_type,\n        COUNT ( DISTINCT v4_4_configuration_history_hosts.host_id )\n        AS host_count\n    FROM  v4_4_statistics_hosts_resources_usage_hourly AS stats_hosts\n        INNER JOIN v4_4_configuration_history_hosts\n            ON (\n                v4_4_configuration_history_hosts.history_id =\n                stats_hosts.host_configuration_version\n            )\n        INNER JOIN v4_4_configuration_history_hosts a\n            ON (\n                a.host_id =\n                stats_hosts.host_id\n            )\n    WHERE\n        v4_4_configuration_history_hosts.cluster_id IN (\n            SELECT v4_4_configuration_history_clusters.cluster_id\n            FROM v4_4_configuration_history_clusters\n            WHERE\n                v4_4_configuration_history_clusters.datacenter_id = '$datacenter_id'\n        )\n        AND v4_4_configuration_history_hosts.cluster_id IN ( '$cluster_id' )\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n        AND a.history_id IN (\n            SELECT MAX ( b.history_id )\n            FROM v4_4_configuration_history_hosts b\n            GROUP BY b.host_id\n        )\n        AND\n            CASE\n                WHEN '$show_deleted' = 'No'\n                    THEN a.delete_date IS NULL\n                ELSE\n                    a.delete_date IS NULL\n                    OR\n                    a.delete_date IS NOT NULL\n            END\n    GROUP BY\n        history_datetime,\n        COALESCE (\n            v4_4_configuration_history_hosts.host_os,\n            'Unknown'\n        )\n) AS a\nGROUP BY\n    history_datetime,\n    os_type, host_count\nORDER BY history_datetime"
    }
   ]
  },
  {
   "title": "Cluster Capacity Vs Usage (BR19)",
   "type": "table",
   "description": "This report contains charts displaying host’s resources usage measurements (CPU core; physical Memory) and charts displaying virtual machine’s resources usage measurements (virtual machine's total vCPU; Virtual Memory size) for a selected cluster.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    host_cpu_cores,\n    vm_cpu_cores_total,\n    host_mem_avg,\n    vm_mem_total\nFROM (\n    SELECT\n        t.history_datetime AS time,\n        host_cpu_cores,\n        host_mem_avg,\n        vm_cpu_cores_total,\n        vm_mem_total\n    FROM (\n        SELECT\n            history_datetime,\n            SUM ( coalesce ( v4_4_configuration_history_hosts.number_of_cores , 0 ) * minutes_in_status ) / SUM ( minutes_in_status ) as host_cpu_cores,\n            SUM ( coalesce ( v4_4_configuration_history_hosts.memory_size_mb , 0 ) * minutes_in_status ) / SUM ( minutes_in_status ) as host_mem_avg\n        FROM v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_configuration_history_hosts\n                ON (\n                    v4_4_configuration_history_hosts.history_id = v4_4_statistics_hosts_resources_usage_samples.host_configuration_version\n                )\n                    INNER JOIN v4_4_configuration_history_hosts latest\n                        ON (\n                            latest.host_id = v4_4_statistics_hosts_resources_usage_samples.host_id\n                        )\n        WHERE v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n            AND v4_4_configuration_history_hosts.cluster_id in (\n                SELECT v4_4_configuration_history_clusters.cluster_id\n                FROM v4_4_configuration_history_clusters\n                WHERE v4_4_configuration_history_clusters.datacenter_id = '$datacenter_id'\n            )\n            AND v4_4_configuration_history_hosts.cluster_id IN ( '$cluster_id' )\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            AND latest.history_id in (\n                SELECT max ( b.history_id )\n                FROM v4_4_configuration_history_hosts b\n                GROUP BY b.host_id\n            )\n            AND\n                CASE\n                    WHEN '$show_deleted' = 'No'\n                        THEN latest.delete_date IS NULL\n                    ELSE\n                        latest.delete_date IS NULL\n                        OR\n                        latest.delete_date IS NOT NULL\n                END\n        GROUP BY history_datetime\n    ) as t\n    INNER JOIN (\n        SELECT\n            nested_query.history_datetime,\n            SUM ( nested_query.cpu_cores ) as vm_cpu_cores_total,\n            SUM ( nested_query.mem_total ) as vm_mem_total\n        FROM (\n            SELECT\n                history_datetime,\n                v4_4_configuration_history_vms.vm_id,\n                SUM ( coalesce ( v4_4_configuration_history_vms.cpu_per_socket , 0 ) * coalesce ( v4_4_configuration_history_vms.number_of_sockets , 0 ) * minutes_in_status ) / SUM ( minutes_in_status ) as cpu_cores,\n                SUM ( coalesce ( v4_4_configuration_history_vms.memory_size_mb , 0 ) * minutes_in_status ) / SUM ( minutes_in_status ) as mem_total\n            FROM v4_4_statistics_vms_resources_usage_samples\n                INNER JOIN v4_4_configuration_history_vms\n                    ON (\n                        v4_4_configuration_history_vms.history_id = v4_4_statistics_vms_resources_usage_samples.vm_configuration_version\n                    )\n                    INNER JOIN v4_4_configuration_history_vms latest\n                        ON (\n                            latest.vm_id = v4_4_statistics_vms_resources_usage_samples.vm_id\n                        )\n            WHERE v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n                AND v4_4_configuration_history_vms.cluster_id in (\n                    SELECT v4_4_configuration_history_clusters.cluster_id\n                    FROM v4_4_configuration_history_clusters\n                    WHERE v4_4_configuration_history_clusters.datacenter_id = '$datacenter_id'\n                )\n                AND v4_4_configuration_history_vms.cluster_id IN ( '$cluster_id' )\n                AND history_datetime >= $__timeFrom()\n                AND history_datetime < $__timeTo()\n                AND latest.history_id in (\n                    SELECT max ( b.history_id )\n                    FROM v4_4_configuration_history_vms b\n                    GROUP BY b.vm_id\n                )\n                AND\n                    CASE\n                        WHEN '$show_deleted' = 'No'\n                            THEN latest.delete_date IS NULL\n                        ELSE\n                            latest.delete_date IS NULL\n                            OR\n                            latest.delete_date IS NOT NULL\n                    END\n            GROUP BY history_datetime, v4_4_configuration_history_vms.vm_id\n        )\n        as nested_query\n        GROUP BY nested_query.history_datetime\n    ) as h\n        ON (\n            h.history_datetime =\n            t.history_datetime\n        )\n)\nas query_run"
    }
   ]
  }
 ]
}