SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u660E\u306E\u30B9\u30C6\u30FC\u30BF\u30B9' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast('Unbekannter Status' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast('Unknown Status' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast('Estatus desconocido' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast('Statut inconnu' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast('Status desconhecidos' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u77E5\u7684\u72B6\u6001' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('In Betrieb' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Up' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Funcionando' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Actif' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u7A3C\u50CD\u4E2D' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Ativo' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E0A\u7EBF\u7684' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Wartung' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Maintenance' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Mantenimiento' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Maintenance' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u30E1\u30F3\u30C6\u30CA\u30F3\u30B9' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Manuten\u00E7\u00E3o' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u7EF4\u62A4' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Problematisch' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Problematic' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Probl\u00E9matic' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u554F\u984C\u3042\u308A' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u6709\u95EE\u9898\u7684' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('de' as varchar(40)),cast('Benutzer' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('en_US' as varchar(40)),cast('User' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('es' as varchar(40)),cast('Usuario' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('fr' as varchar(40)),cast('Utililisateur' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('ja' as varchar(40)),cast('\u30E6\u30FC\u30B6\u30FC' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('pt_BR' as varchar(40)),cast('Usu\u00E1rio' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('zh_CN' as varchar(40)),cast('\u7528\u6237' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('de' as varchar(40)),cast('Benutzergruppe' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('en_US' as varchar(40)),cast('User Group' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('es' as varchar(40)),cast('Grupo de usuarios' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('fr' as varchar(40)),cast('Groupe d''utilisateurs' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('ja' as varchar(40)),cast('\u30E6\u30FC\u30B6\u30FC\u30B0\u30EB\u30FC\u30D7' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('pt_BR' as varchar(40)),cast('Grupo de Usu\u00E1rio' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('zh_CN' as varchar(40)),cast('\u7528\u6237\u7EC4' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('de' as varchar(40)),cast('Marke' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('en_US' as varchar(40)),cast('Tag' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('es' as varchar(40)),cast('Etiqueta' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('fr' as varchar(40)),cast('Balise' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('ja' as varchar(40)),cast('\u30BF\u30B0' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('pt_BR' as varchar(40)),cast('Tag' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('zh_CN' as varchar(40)),cast('\u6807\u7B7E' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u4EEE\u60F3\u30DE\u30B7\u30F3' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u865A\u62DF\u673A' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('H\u00F4te' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u30DB\u30B9\u30C8' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E3B\u673A' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast('VM-Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast('VM Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast('Pool MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast('VM Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast('\u4EEE\u60F3\u30DE\u30B7\u30F3\u30D7\u30FC\u30EB' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast('Pool da MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast('\u865A\u62DF\u673A\u6C60' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast('Unbekannter Status' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast('Unknown Status' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast('Estatus desconocido' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast('Statut inconnu' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u660E\u306E\u30B9\u30C6\u30FC\u30BF\u30B9' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast('Status desconhecidos' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u77E5\u7684\u72B6\u6001' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('In Betrieb' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Up' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Funcionando' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Actif' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u7A3C\u50CD\u4E2D' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Ativo' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E0A\u7EBF\u7684' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Wartung' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Maintenance' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Mantenimiento' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Maintenance' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u30E1\u30F3\u30C6\u30CA\u30F3\u30B9' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Manuten\u00E7\u00E3o' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u7EF4\u62A4' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Problematisch' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Problematic' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Probl\u00E9matic' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u554F\u984C\u3042\u308A' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u6709\u95EE\u9898\u7684' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('RHEV' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('pv' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Unbekannt' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Unknown' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Desconocido' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Inconnu' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u660E' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Desconhecido' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u77E5\u7684' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('de' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('en_US' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('es' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('fr' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('ja' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('de' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('en_US' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('es' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('fr' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('ja' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('de' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('en_US' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('es' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('fr' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('ja' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('de' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('en_US' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('es' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('fr' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('ja' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('de' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('en_US' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('es' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('fr' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('ja' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('de' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('en_US' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('es' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('fr' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('ja' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('de' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('en_US' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('es' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('fr' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('ja' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('de' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('en_US' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('es' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('fr' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('ja' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('de' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('en_US' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('es' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('fr' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('ja' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('de' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('en_US' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('es' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('fr' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('ja' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast('Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast('Andere Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast('Other Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast('Otro Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast('Autre Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast('\u305D\u306E\u4ED6\u306E Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast('Outro Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast('\u5176\u4ED6 Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('de' as varchar(40)),cast('Sonstige' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('en_US' as varchar(40)),cast('Other' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('es' as varchar(40)),cast('Otros' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('fr' as varchar(40)),cast('Autre' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('ja' as varchar(40)),cast('\u305D\u306E\u4ED6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('pt_BR' as varchar(40)),cast('Outro' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('zh_CN' as varchar(40)),cast('\u5176\u4ED6\u7684' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('de' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('en_US' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('es' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('fr' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('ja' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('de' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('en_US' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('es' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('fr' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('ja' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('de' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('en_US' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('es' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('fr' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('ja' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('pt_BR' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('zh_CN' as varchar(40)),cast('RHEL 3' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Alle' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('All' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Todos' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Tous' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u3059\u3079\u3066' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Todos' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u5168\u90E8' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Abgeh\u00E4ngt von ' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Detached on' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Separado el' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('D\u00E9tach\u00E9 sur' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30BF\u30C3\u30C1\u3055\u308C\u305F\u65E5\u4ED8' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Desanexado no' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u9644\u52A0\u5728' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Keine verf\u00FCgbar' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('None Available' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Ninguno disponible' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Aucunes Disponible' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30FC\u30BF\u304C\u3042\u308A\u307E\u305B\u3093' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Nada Encontrado' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u6CA1\u6709\u53EF\u7528\u7684' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('T\u00E4glich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Daily' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Diariamente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Chaque jour' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u65E5\u6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Di\u00E1rio' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u6309\u65E5' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Monatlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Monthly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Mensualmente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Chaque mois' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u6708\u6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Mensal' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u6309\u6708' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Viertelj\u00E4hrlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Quarterly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Cada cuarto' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Tous les 3 mois' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u56DB\u534A\u671F' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Trimestral' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u6309\u5B63\u5EA6' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('J\u00E4hrlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Yearly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Anualmente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Chaque ann\u00E9e' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u5E74\u6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Anual' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u6309\u5E74\u5EA6' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Entfernt auf ' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Removed on' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Borrado el' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Supprim\u00E9 de' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u524A\u9664\u3055\u308C\u305F\u65E5\u4ED8' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Removido no' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u5DF2\u5220\u9664' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Nein' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('No' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('No' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Non' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u3044\u3044\u3048' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('N\u00E3o' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u5426' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Ja' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Yes' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Si' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Oui' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u306F\u3044' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Sim' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u662F' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Getrennt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Unattached' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Separado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Non attach\u00E9' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u672A\u30A2\u30BF\u30C3\u30C1' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Desanexado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u9644\u52A0\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Aktiv' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Active' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Activo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Actif' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u30A2\u30AF\u30C6\u30A3\u30D6' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Ativar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u6D3B\u52A8\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Inaktiv' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('InActive' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Inactivo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Inactif' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u975E\u30A2\u30AF\u30C6\u30A3\u30D6' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Inativo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E0D\u6D3B\u52A8\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Gemischt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Mixed' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Mezclado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Mixte' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u6DF7\u5728' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Mesclado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u6DF7\u5408\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast('Gesperrt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast('Locked' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast('Bloqueado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast('Verrouill\u00E9' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast('\u30ED\u30C3\u30AF' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast('Bloqueado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast('\u9501\u4F4F\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Daten (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Data (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Datos (Maestro)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Donn\u00E9es (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30FC\u30BF (\u30DE\u30B9\u30BF\u30FC)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Dados (Mestre)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u6570\u636E\uFF08\u4E3B\uFF09' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Daten' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Data' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Datos' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Donn\u00E9es' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30FC\u30BF' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Dados' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u6570\u636E' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Exportar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u30A8\u30AF\u30B9\u30DD\u30FC\u30C8' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Exportar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u5BFC\u51FA' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Unbekannt' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Unknown' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Desconocido' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Inconnu' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u660E' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Desconhecido' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u77E5\u7684' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast('Lokal' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast('Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast('Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast('Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast('\u30ED\u30FC\u30AB\u30EB' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast('Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast('Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('de' as varchar(40)),cast('Alle' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('en_US' as varchar(40)),cast('All' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('es' as varchar(40)),cast('Todos' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('fr' as varchar(40)),cast('Tous' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('ja' as varchar(40)),cast('\u3059\u3079\u3066' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('pt_BR' as varchar(40)),cast('Todos' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('zh_CN' as varchar(40)),cast('\u5168\u90E8' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Aktiviert' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Enabled' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Habilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Activ\u00E9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u6709\u52B9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Habilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u542F\u7528' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Inaktiv' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Disabled' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Inhabilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('D\u00E9sactiv\u00E9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u7121\u52B9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Desabilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u7981\u7528' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Non assign\u00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u672A\u5272\u308A\u5F53\u3066' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('N\u00E3o determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u5206\u914D\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast('COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast('Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Non assign\u00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u672A\u5272\u308A\u5F53\u3066' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('N\u00E3o Determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u5206\u914D\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Gesperrt' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Locked' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Bloqueado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Verrouill\u00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u30ED\u30C3\u30AF' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Bloqueado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u9501\u4F4F\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Ung\u00FCltig' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Invalid' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Inv\u00E1lido' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Invalide' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u7121\u52B9' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Inv\u00E1lido' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u65E0\u6548\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast('Verboten' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast('Illegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast('Ilegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast('Ill\u00E9gal(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u6B63' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast('Ilegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast('\u975E\u6CD5\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Non assign\u00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u672A\u5272\u308A\u5F53\u3066' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('N\u00E3o determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u5206\u914D\u7684' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('System' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('System' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Sistema' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Syst\u00E8me' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u30B7\u30B9\u30C6\u30E0' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Sistema' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u7CFB\u7EDF' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Daten' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Data' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('Datos' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Donn\u00E9es' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30FC\u30BF' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Dados' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u6570\u636E' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast('Unbekannter Status' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast('Unknown Status' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast('Estatus desconocido' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast('Statut inconnu' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast('\u4E0D\u660E\u306E\u30B9\u30C6\u30FC\u30BF\u30B9' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast('Status Desconhecido' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast('\u672A\u77E5\u7684\u72B6\u6001' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Au\u00DFer Betrieb' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Down' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('No funciona' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Inactif' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u505C\u6B62\u4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Inativo' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E0B\u7EBF\u7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('In Betrieb' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Up' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Funcionando' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Actif' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u7A3C\u50CD\u4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Ativado' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u4E0A\u7EBF\u7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast('Angehalten' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast('Paused' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast('En pausa' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast('Sur pause' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast('\u4E00\u6642\u505C\u6B62\u4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast('Pausado' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast('\u6682\u505C\u7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast('Problematisch' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast('Problematic' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast('Probl\u00E9matic' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast('\u554F\u984C\u3042\u308A' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast('Problem\u00E1tico' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast('\u6709\u95EE\u9898\u7684' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast('Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast('Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast('Escritorio' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast('Bureau' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast('\u30C7\u30B9\u30AF\u30C8\u30C3\u30D7' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast('Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast('\u684C\u9762' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast('Server' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast('Server' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast('Servidor' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast('Serveur' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast('\u30B5\u30FC\u30D0\u30FC' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast('Servidor' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast('\u670D\u52A1\u5668' as text));
