{
 "title": "Cluster Dashboard",
 "description": "The cluster dashboard displays the latest configurations, resources status and usages percent of the clusters entities.",
 "tags": [
  "Host",
  "VM",
  "Cluster",
  "HA",
  "CPU",
  "Memory",
  "Downtime",
  "Uptime"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" },
   {
    "name": "datacenter_id",
    "label": "Data Canter",
    "query": "SELECT DISTINCT\n    datacenter_name AS __text, \n    datacenter_id AS __value\nFROM v4_4_latest_configuration_datacenters"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT \n    cluster_name AS __text, \n    cluster_id AS __value \nFROM v4_4_latest_configuration_clusters \nWHERE datacenter_id IN ('$datacenter_id')"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "\n###### The cluster dashboard displays the latest configurations, resources status and usage percent of the clusters entities.\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Number of Hosts (DR3)",
   "type": "singlestat",
   "description": "Number of hosts in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR3 - This query returns the\n-- number of hosts and the number of vms\n-- in the latest cluster configuration\n\n-- This query returns the number of active hosts in a chosen cluster\nSELECT\n    COUNT ( DISTINCT v4_4_latest_configuration_hosts.host_id ) AS host_count\nFROM \n    v4_4_latest_configuration_hosts\n    INNER JOIN v4_4_latest_configuration_vms\n        ON \n            (\n                v4_4_latest_configuration_hosts.cluster_id =\n                v4_4_latest_configuration_vms.cluster_id\n            )\nWHERE\n    --Here we filter by the cluster chosen by the user\n    v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )"
    }
   ]
  },
  {
   "title": "Number of Virtual Machines (DR3)",
   "type": "singlestat",
   "description": "Number of virtual machines in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR3 - This query returns the\n-- number of hosts and the number of vms\n-- in the latest cluster configuration\n\n-- This query returns the number of active vms in a chosen cluster\nSELECT\n    COUNT ( DISTINCT v4_4_latest_configuration_vms.vm_id ) AS vm_count\nFROM \n    v4_4_latest_configuration_hosts\n    INNER JOIN v4_4_latest_configuration_vms\n        ON \n            (\n                v4_4_latest_configuration_hosts.cluster_id =\n                v4_4_latest_configuration_vms.cluster_id\n            )\nWHERE\n    --Here we filter by the cluster chosen by the user\n    v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )"
    }
   ]
  },
  {
   "title": "Cluster Host Uptime (DR6)",
   "type": "singlestat",
   "description": "Average uptime percent for the hosts in the specific cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR6 - This query returns the average\n-- uptime percent for the hosts in the specific cluster\n\nSELECT\n    (\n        -- Here we sum the total uptime\n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n                        THEN COALESCE ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        /\n        -- Here we sum the total time\n        SUM \n            (\n                v4_4_statistics_hosts_resources_usage_samples.minutes_in_status\n            )\n    ) * 100 AS uptime_mins_percent\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_hosts\n        ON \n            (\n                v4_4_latest_configuration_hosts.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )\nWHERE\n    -- Here we filter by the cluster chosen by the user\n    v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )"
    }
   ]
  },
  {
   "title": "Cluster Host CPU Usage (DR12)",
   "type": "singlestat",
   "description": "Average percentage of CPU usage for all hosts in the selected cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR12 - This query returns the average\n-- resources that are used ( cpu and memory )\n-- for the hosts in the specific cluster\n\nSELECT\n    cpu_usage_percent_avg AS average_cpu_used\nFROM \n    (\n        SELECT\n            AVG ( cpu_usage_percent ) AS cpu_usage_percent_avg\n        FROM \n            v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_statistics_hosts_resources_usage_samples.host_id\n                    )\n        WHERE\n            -- Here we get only active hosts\n            v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n            -- Here we filter by the cluster chosen by the user\n            AND v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )\n    ) AS average_cpu_percent"
    }
   ]
  },
  {
   "title": "Cluster Host Memory Usage (DR12)",
   "type": "singlestat",
   "description": "Average percentage of memory usage for all hosts in the selected cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR12 - This query returns the average\n-- resources that are used ( cpu and memory )\n-- for the hosts in the specific cluster\n\nSELECT\n    memory_usage_percent_avg AS average_memory_used\nFROM \n    (\n        SELECT\n            AVG ( memory_usage_percent ) AS memory_usage_percent_avg\n        FROM \n            v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_statistics_hosts_resources_usage_samples.host_id\n                    )\n        WHERE\n            -- Here we get only active hosts\n            v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n            -- Here we filter by the cluster chosen by the user\n            AND v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )\n    ) AS average_memory_percent\n"
    }
   ]
  },
  {
   "title": "Cluster High Availability Virtual Machine Uptime (DR13)",
   "type": "singlestat",
   "description": "Uptime percent of high availability virtual machines.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "-- DR13 - This query returns the\n-- uptime percent of high availability vms\n-- for the specific cluster\n\nSELECT\n    (\n        -- Here we sum the total uptime\n        SUM\n            (\n                CASE\n                    WHEN v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n                        THEN COALESCE ( v4_4_statistics_vms_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        /\n        -- Here we sum the total time    \n        SUM \n            (\n                v4_4_statistics_vms_resources_usage_samples.minutes_in_status\n            )\n    ) * 100 AS uptime_mins_percent\nFROM \n    v4_4_statistics_vms_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_vms\n        ON \n            (\n                v4_4_latest_configuration_vms.vm_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_id\n            )\nWHERE\n    -- Here we get only high availability vms\n    v4_4_latest_configuration_vms.high_availability = TRUE\n    -- Here we filter by the cluster chosen by the user\n    AND v4_4_latest_configuration_vms.cluster_id = CAST ( '$cluster_id' AS UUID )"
    }
   ]
  },
  {
   "title": "Cluster Summary of Host Resource Peaks (DR28)",
   "type": "table",
   "description": "Average CPU and memory peaks per host for the specific cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "-- DR28 - This query returns the\n-- average cpu and memory peaks per host\n-- for the specific cluster\n\nSELECT\n    'No' AS is_deleted,\n    host_id,\n    host_name,\n    AVG ( cpu_peak ) AS avg_cpu_peak,\n    AVG ( mem_peak ) AS avg_mem_peak\nFROM \n    (\n        -- Calculation of samples cpu and memory usage peaks\n        SELECT\n            v4_4_latest_configuration_hosts.host_id,\n            v4_4_latest_configuration_hosts.host_name,\n            MAX ( cpu_usage_percent ) AS cpu_peak,\n            MAX ( memory_usage_percent ) AS mem_peak\n        FROM \n            v4_4_statistics_hosts_resources_usage_samples\n            INNER JOIN v4_4_latest_configuration_hosts\n                ON \n                    (\n                        v4_4_latest_configuration_hosts.host_id =\n                        v4_4_statistics_hosts_resources_usage_samples.host_id\n                    )\n        WHERE\n            -- Here we filter by active hosts only\n            v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n            -- Here we filter by the cluster chosen by the user\n            AND v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )\n        GROUP BY\n            v4_4_latest_configuration_hosts.host_id,\n            v4_4_latest_configuration_hosts.host_name,\n            DATE_TRUNC ( 'hour', v4_4_statistics_hosts_resources_usage_samples.history_datetime )\n    ) AS tbl_samples_peaks\nGROUP BY host_id, host_name"
    }
   ]
  },
  {
   "title": "Cluster Top 5 Busiest Hosts (DR23)",
   "type": "table",
   "description": "CPU and memory usage for the top 5 busiest hosts.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "-- DR23 - This query returns the\n-- cpu and memory usage for the\n-- top 5 busiest hosts in the specific cluster\n\nSELECT\n    'No' AS is_deleted,\n    v4_4_latest_configuration_hosts.host_id,\n    v4_4_latest_configuration_hosts.host_name,\n    AVG ( cpu_usage_percent ) AS cpu_usage_percent_avg,\n    MAX ( cpu_usage_percent ) AS cpu_usage_percent_max,\n    AVG ( memory_usage_percent ) AS memory_usage_percent_avg,\n    MAX ( memory_usage_percent ) AS memory_usage_percent_max\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_hosts\n        ON \n            (\n                v4_4_latest_configuration_hosts.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )\nWHERE\n    -- Here we get only active hosts\n    v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n    -- Here we filter by the cluster chosen by the user\n    AND v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )\nGROUP BY\n    v4_4_latest_configuration_hosts.host_id,\n    v4_4_latest_configuration_hosts.host_name\nORDER BY\n    AVG ( cpu_usage_percent ) +\n    MAX ( cpu_usage_percent ) +\n    AVG ( memory_usage_percent ) +\n    MAX ( memory_usage_percent ) \n    DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Cluster Virtual Machine CPU Overcommit (DR14)",
   "type": "graph",
   "description": "Average number of CPU Cores for the hosts and virtual machines in the specific cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- DR14 - This query returns the\n-- average number of CPU Cores and memory\n-- for the hosts and vms in the specific cluster.\n\n-- Average hosts CPU cores\nSELECT\n    NOW () AS time,\n    'Avg. Hosts CPU Cores' AS entity,\n    -- Calculation of samples average hosts CPU cores \n    SUM \n        (\n            COALESCE ( v4_4_configuration_history_hosts.number_of_cores, 0 ) \n            *\n            minutes_in_status\n        ) \n    / SUM ( minutes_in_status ) AS cpu_cores_hosts\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_configuration_history_hosts\n        ON \n            (\n                v4_4_configuration_history_hosts.history_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_configuration_version\n            )\n    INNER JOIN v4_4_latest_configuration_hosts AS a\n        ON \n            (\n                a.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )\nWHERE\n    -- Here we get only active hosts\n    v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n    -- Here we filter by the cluster chosen by the user\n    AND a.cluster_id = CAST ( '$cluster_id' AS UUID )\n\nUNION ALL\n\n-- Average vms CPU cores \nSELECT\n    NOW () AS time,\n    'Avg. VMs CPU Cores' AS entity,\n    SUM ( nested_query.cpu_cores ) AS cpu_cores_vms\nFROM \n    (\n        SELECT\n            a.vm_id,\n            -- Calculation of samples average vms CPU cores \n            SUM \n                (\n                    COALESCE ( v4_4_configuration_history_vms.cpu_per_socket, 0 )\n                    *\n                    COALESCE ( v4_4_configuration_history_vms.number_of_sockets, 0 )\n                    *\n                    minutes_in_status\n                ) / SUM ( minutes_in_status ) AS cpu_cores\n        FROM \n            v4_4_statistics_vms_resources_usage_samples\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        v4_4_statistics_vms_resources_usage_samples.vm_configuration_version\n                    )\n            INNER JOIN v4_4_latest_configuration_vms AS a\n                ON \n                    (\n                        a.vm_id =\n                        v4_4_statistics_vms_resources_usage_samples.vm_id\n                    )\n        WHERE\n            -- Here we get only active vms\n            v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n            -- Here we filter by the cluster chosen by the user\n            AND a.cluster_id = CAST ( '$cluster_id' AS uuid )\n        GROUP BY a.vm_id\n    ) AS nested_query"
    }
   ]
  },
  {
   "title": "Cluster Virtual Machine Memory Overcommit (DR14)",
   "type": "graph",
   "description": "Average memory for the hosts and virtual machines in the specific cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- DR14 - This query returns the\n-- average number of CPU cores and memory\n-- for the hosts and vms in the specific cluster.\n\n-- Average hosts memory\nSELECT\n    NOW () AS time,\n    'Avg. Hosts Memory' AS entity,\n    -- Calculation of samples average hosts memory \n    SUM (\n        COALESCE ( v4_4_configuration_history_hosts.memory_size_mb, 0 ) \n        *\n        minutes_in_status\n        ) \n    / SUM ( minutes_in_status ) AS mem_avg_hosts\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_configuration_history_hosts\n        ON \n            (\n                v4_4_configuration_history_hosts.history_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_configuration_version\n            )\n    INNER JOIN v4_4_latest_configuration_hosts AS a\n        ON \n            (\n                a.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )\nWHERE\n    -- Here we get only active hosts\n    v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n    -- Here we filter by the cluster chosen by the user\n    AND a.cluster_id = CAST ( '$cluster_id' AS UUID )\n\nUNION ALL\n\n-- Average vms memory\nSELECT\n    NOW () AS time,\n    'Avg. VMs Memory' AS entity,\n    SUM ( nested_query.mem_avg ) AS mem_avg_vms\nFROM \n    (\n        SELECT\n            a.vm_id,\n            -- Calculation of samples average vms memory  \n            SUM \n                (\n                    COALESCE ( v4_4_configuration_history_vms.memory_size_mb, 0 ) \n                    *\n                    minutes_in_status\n                ) / SUM ( minutes_in_status ) AS mem_avg\n        FROM \n            v4_4_statistics_vms_resources_usage_samples\n            INNER JOIN v4_4_configuration_history_vms\n                ON \n                    (\n                        v4_4_configuration_history_vms.history_id =\n                        v4_4_statistics_vms_resources_usage_samples.vm_configuration_version\n                    )\n            INNER JOIN v4_4_latest_configuration_vms AS a\n                ON \n                    (\n                        a.vm_id =\n                        v4_4_statistics_vms_resources_usage_samples.vm_id\n                    )\n        WHERE\n            -- Here we get only active vms\n            v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n            -- Here we filter by the cluster chosen by the user\n            AND a.cluster_id = CAST ( '$cluster_id' AS uuid )\n        GROUP BY a.vm_id\n) AS nested_query"
    }
   ]
  },
  {
   "title": "Top Five High Availability Virtual Machines Downtime (DR20)",
   "type": "table",
   "description": "This report displays the total uptime and planned downtime percentage for the 5 high availability virtual machines that have the lowest uptime.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "-- DR20 - This query returns for 5 high availability vms,\n-- that have the least uptime percent,\n-- the total uptime and planned downtime percent per vm.\n\nSELECT\n    'No' AS is_deleted,\n    v4_4_latest_configuration_vms.vm_id, \n    v4_4_latest_configuration_vms.vm_name,\n    (\n        -- Calculation of samples vm uptime \n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_vms_resources_usage_samples.vm_status = 1\n                        THEN COALESCE ( v4_4_statistics_vms_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        / SUM ( v4_4_statistics_vms_resources_usage_samples.minutes_in_status )\n    ) * 100 AS uptime_percent,\n    (\n        -- Calculation of samples vm planned downtime \n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_vms_resources_usage_samples.vm_status IN ( 0, 2 )\n                        THEN COALESCE ( v4_4_statistics_vms_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        / SUM ( v4_4_statistics_vms_resources_usage_samples.minutes_in_status )\n    ) * 100 AS planned_downtime_percent\nFROM \n    v4_4_statistics_vms_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_vms\n        ON \n            (\n                v4_4_latest_configuration_vms.vm_id =\n                v4_4_statistics_vms_resources_usage_samples.vm_id\n            )\nWHERE\n    -- Here we filter by the cluster chosen by the user\n    v4_4_latest_configuration_vms.cluster_id = CAST ( '$cluster_id' AS UUID )\n    -- Here we get only high availability vms\n    AND v4_4_latest_configuration_vms.high_availability = TRUE\nGROUP BY\n    -- For the calculations to be per vm \n    v4_4_latest_configuration_vms.vm_id,\n    v4_4_latest_configuration_vms.vm_name\nORDER BY uptime_percent ASC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Top Five Hosts Downtime (DR18)",
   "type": "table",
   "description": "This report displays the total uptime and planned and unplanned downtime percentage for the 5 hosts that have the lowest uptime.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "-- DR18 - This query returns for 5 hosts,\n-- that have the least uptime percent, \n-- the total uptime, planned and unplanned \n-- downtime percent per host.\n\nSELECT\n    'No' AS is_deleted,\n    v4_4_latest_configuration_hosts.host_id,\n    v4_4_latest_configuration_hosts.host_name,\n    (\n        -- Calculation of samples host uptime \n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_hosts_resources_usage_samples.host_status = 1\n                        THEN COALESCE ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        / SUM ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status )\n    ) * 100 AS uptime_percent,\n    (\n        -- Calculation of samples host planned downtime \n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_hosts_resources_usage_samples.host_status = 2\n                        THEN COALESCE ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status, 0 )\n                ELSE 0\n                END\n            ) \n        / SUM ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status )\n    ) * 100 AS planned_downtime_percent,\n    (\n        -- Calculation of samples host unplanned downtime \n        SUM \n            (\n                CASE\n                    WHEN v4_4_statistics_hosts_resources_usage_samples.host_status = 3\n                        THEN COALESCE ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status, 0 )\n                    ELSE 0\n                END\n            ) \n        /\n        SUM ( v4_4_statistics_hosts_resources_usage_samples.minutes_in_status )\n    ) * 100 AS unplanned_downtime_percent\nFROM \n    v4_4_statistics_hosts_resources_usage_samples\n    INNER JOIN v4_4_latest_configuration_hosts\n        ON \n            (\n                v4_4_latest_configuration_hosts.host_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_id\n            )\nWHERE\n    -- Here we filter by the cluster chosen by the user\n    v4_4_latest_configuration_hosts.cluster_id = CAST ( '$cluster_id' AS UUID )\nGROUP BY\n    -- For the calculations to be per host\n    v4_4_latest_configuration_hosts.host_id,\n    v4_4_latest_configuration_hosts.host_name\nORDER BY\n    uptime_percent ASC,\n    unplanned_downtime_percent DESC,\n    planned_downtime_percent DESC\nLIMIT 5"
    }
   ]
  }
 ]
}