{
 "title": "Hosts Trend Dashboard",
 "description": "The hosts trend dashboard displaying resources measurements over time - number of virtual machines, CPU, memory, and ethernet interface Tx/Rx.",
 "tags": [
  "Host",
  "Cluster",
  "CPU",
  "Memory",
  "Interface"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT   \n    CAST ( datacenter_id AS varchar ) AS __value,  \n    CASE          \n        WHEN delete_date IS NULL  \t     \t    \n            THEN datacenter_name \t \t\n        WHEN delete_date IS NOT null  \t      \t    \n            THEN datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \n    END AS __text  \t\t\nFROM v4_4_configuration_history_datacenters  \t\t\nWHERE       \t\t    \n    history_id           \t\t\t    \n        IN               \t\t\t\t\n            (  \t             \t\t\t\t\t\n                SELECT MAX ( a.history_id )  \t\t         \t\t\t\t\t\n                FROM v4_4_configuration_history_datacenters a  \t\t         \t\t\t\t\t\n                GROUP BY a.datacenter_id \t         \t\t\t\t\n            ) \t \t\t\t\n    AND datacenter_id  \t         \t\t\t    \n        IN \t\t\t     \t\t\t\t    \n            ( \t\t\t\t\t \t\t\t\t\t\t\n                SELECT DISTINCT datacenter_id \t\t\t\t\t \t\t\t\t\t\t\n                FROM v4_4_configuration_history_clusters \t\t\t\t\t \t\t\t\t\t\t\n                WHERE  \t\t\t\t\t     \t\t\t\t\t\t    \n                    cluster_id \t\t\t\t\t         \t\t\t\t\t\t        \n                        IN \t\t\t\t\t             \t\t\t\t\t\t            \n                            ( \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\t\n                                SELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\t\n                                FROM v4_4_configuration_history_hosts  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\n                            ) \t\t\t\t\t\n            ) \t \t\t\t\n    AND \t    \t\t\t    \n        CASE  \t        \t\t\t\t    \n            WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    \n                THEN 1=1 \t\t    \t\t\t\t\t\n            WHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    \n                THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t                \n        END"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT        \n    CAST ( cluster_id AS varchar ) AS __value,  \t\n    CASE      \t    \n        WHEN delete_date IS NULL  \t     \t\t    \n            THEN cluster_name \t \t\t\n        WHEN delete_date IS NOT null  \t      \t\t    \n            THEN cluster_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \t\n    END AS __text  \t\nFROM v4_4_configuration_history_clusters  \t\nWHERE       \t    \n    history_id           \t\t    \n        IN               \t\t\t    \n            (  \t             \t\t\t\t\t\n                SELECT MAX ( a.history_id )  \t\t         \t\t\t\t\t\n                FROM v4_4_configuration_history_clusters a  \t\t         \t\t\t\t\t\n                GROUP BY a.cluster_id \t         \t\t\t\t\n            ) \t \t\t\n    AND cluster_id  \t\t    \n        IN \t\t\t     \t\t\t    \n            ( \t\t\t\t\t \t\t\t\t\t\n                SELECT DISTINCT cluster_id \t\t\t\t\t \t\t\t\t\t\n                FROM v4_4_configuration_history_hosts \t\t\t\t \t\t\t\t\n            ) \t\t\n    AND \t    \t\t    \n        CASE  \t        \t\t\t    \n            WHEN '$show_deleted'='Yes' \t            \t\t\t\t    \n                THEN 1=1 \t\t    \t\t\t\t\n            WHEN '$show_deleted'='No' \t\t        \t\t\t\t    \n                THEN v4_4_configuration_history_clusters.delete_date ISNULL \t    \t\t\t\n        END     \t\t\n    AND datacenter_id IN ($datacenter_id)"
   },
   {
    "name": "host_id",
    "label": "Host",
    "query": "SELECT DISTINCT   \n    CAST ( host_id AS varchar ) AS __value,  \n    CASE          \n        WHEN delete_date IS NULL  \t     \t    \n            THEN host_name \t \t\n        WHEN delete_date IS NOT null  \t      \t    \n            THEN host_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \n    END AS __text  \t\t\nFROM v4_4_configuration_history_hosts  \t\t\nWHERE       \t\t    \n    history_id           \t\t\t    \n        IN               \t\t\t\t\n            (  \t             \t\t\t\t\t\n                SELECT MAX ( a.history_id )  \t\t         \t\t\t\t\t\n                FROM v4_4_configuration_history_hosts a  \t\t         \t\t\t\t\t\n                GROUP BY a.host_id \t         \t\t\t\t\n            ) \t \t\t\t\n    AND cluster_id IN ($cluster_id)  \t\t\t\n    AND \t    \t\t\t    \n        CASE  \t        \t\t\t\t    \n            WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    \n                THEN 1=1 \t\t    \t\t\t\t\t\n            WHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    \n                THEN v4_4_configuration_history_hosts.delete_date ISNULL \t                \n        END "
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "\n###### This dashboard displays resource measurements (number of virtual machines, CPU, memory, and ethernet interface Tx/Rx) for a selected host over a selected period.\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Hosts Memory Size (over time)",
   "type": "graph",
   "description": "This report displays the memory size for the hosts in the selected cluster, and over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- This report returns the cpu cores and memory size over time\n-- for the hosts in the selected cluster.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Memory size\nSELECT DISTINCT\n    $__time(history_datetime),\n    SUM ( ROUND ( CAST ( COALESCE ( memory_size_mb, 0.00 ) AS float ) :: numeric / 1024, 1 ) ) AS \"Total Memory Size\"\nFROM\n    v4_4_configuration_history_hosts\n    INNER JOIN\n    v4_4_statistics_hosts_resources_usage_samples\n        ON\n            (\n                v4_4_configuration_history_hosts.history_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_configuration_version\n            )\nWHERE \n    -- Show data only when the selected period is up to 24 hours back\n    $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_hosts.host_id IN ($host_id)\n    AND history_datetime >= $__timeFrom() \n    AND history_datetime < $__timeTo()\n    AND    \n        CASE\n            WHEN '$show_deleted'='Yes'\n                THEN 1=1\n            WHEN '$show_deleted'='No'\n                THEN delete_date isnull\n        END\nGROUP BY history_datetime\nORDER BY history_datetime"
    },
    {
     "rawSql": "-- This report returns the cpu cores and memory size over time\n-- for the hosts in the selected cluster.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Memory size\nSELECT DISTINCT\n    $__time(history_datetime),\n    SUM ( ROUND ( CAST ( COALESCE ( memory_size_mb, 0.00 ) AS float ) :: numeric / 1024, 1 ) ) AS \"Total Memory Size\"\nFROM\n    v4_4_configuration_history_hosts\n    INNER JOIN\n    (\n            SELECT history_datetime, host_configuration_version\n            FROM v4_4_statistics_hosts_resources_usage_hourly\n        UNION\n            SELECT history_datetime, host_configuration_version\n            FROM v4_4_statistics_hosts_resources_usage_daily\n            WHERE\n                history_datetime <\n                    (\n                        SELECT MIN ( history_datetime )\n                        FROM v4_4_statistics_hosts_resources_usage_hourly\n                    )\n    ) AS hourly_daily\n        ON\n            (\n                v4_4_configuration_history_hosts.history_id =\n                hourly_daily.host_configuration_version\n            )\nWHERE \n    -- Show data only when the selected period is more then 24 hours back\n    $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_hosts.host_id IN ($host_id)\n    AND history_datetime >= $__timeFrom() \n    AND history_datetime < $__timeTo()\n    AND\n        CASE\n            WHEN '$show_deleted'='Yes'\n                THEN 1=1\n            WHEN '$show_deleted'='No'\n                THEN delete_date isnull\n        END\nGROUP BY history_datetime\nORDER BY history_datetime"
    }
   ]
  },
  {
   "title": "Hosts CPU Cores (over time)",
   "type": "graph",
   "description": "This report displays the CPU cores for the hosts in the selected cluster, and over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- This report returns the cpu cores and memory size over time\n-- for the hosts in the selected cluster.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- CPU cores\nSELECT DISTINCT\n    $__time(history_datetime),\n    SUM ( number_of_cores ) AS \"Total CPU Cores\"\nFROM\n    v4_4_configuration_history_hosts\n    INNER JOIN\n    v4_4_statistics_hosts_resources_usage_samples\n        ON\n            (\n                v4_4_configuration_history_hosts.history_id =\n                v4_4_statistics_hosts_resources_usage_samples.host_configuration_version\n            )\nWHERE \n    -- Show data only when the selected period is up to 24 hours back\n    $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_hosts.host_id IN ($host_id)\n    AND history_datetime >= $__timeFrom() \n    AND history_datetime < $__timeTo()\n    AND    \n        CASE\n            WHEN '$show_deleted'='Yes'\n                THEN 1=1\n            WHEN '$show_deleted'='No'\n                THEN delete_date isnull\n        END\nGROUP BY history_datetime\nORDER BY history_datetime"
    },
    {
     "rawSql": "-- This report returns the cpu cores and memory size over time\n-- for the hosts in the selected cluster.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- CPU cores\nSELECT DISTINCT\n    $__time(history_datetime),\n    SUM ( number_of_cores ) AS \"Total CPU Cores\"\nFROM\n    v4_4_configuration_history_hosts\n    INNER JOIN\n    (\n            SELECT history_datetime, host_configuration_version\n            FROM v4_4_statistics_hosts_resources_usage_hourly\n        UNION\n            SELECT history_datetime, host_configuration_version\n            FROM v4_4_statistics_hosts_resources_usage_daily\n            WHERE\n                history_datetime <\n                    (\n                        SELECT MIN ( history_datetime )\n                        FROM v4_4_statistics_hosts_resources_usage_hourly\n                    )\n    ) AS hourly_daily\n        ON\n            (\n                v4_4_configuration_history_hosts.history_id =\n                hourly_daily.host_configuration_version\n            )\nWHERE \n    -- Show data only when the selected period is more then 24 hours back\n    $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n    AND v4_4_configuration_history_hosts.host_id IN ($host_id)\n    AND history_datetime >= $__timeFrom() \n    AND history_datetime < $__timeTo()\n    AND\n        CASE\n            WHEN '$show_deleted'='Yes'\n                THEN 1=1\n            WHEN '$show_deleted'='No'\n                THEN delete_date isnull\n        END\nGROUP BY history_datetime\nORDER BY history_datetime"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average Memory Usage and Peaks (over time) (BR2A)",
   "type": "graph",
   "description": "This report displays average memory usage and peaks for a selected host over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the hosts\n-- memory usage over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    MEM_Usage AS \"Memory Usage\"\nFROM \n    (\n        -- Hosts Max and Average Memory Usage Peaks\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage\n        FROM v4_4_statistics_hosts_resources_usage_samples AS samples\n        WHERE\n            -- Here we filter by active hosts only\n            samples.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND samples.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, MEM_Usage\nORDER BY sub_query.time"
    },
    {
     "rawSql": "-- BR2A - This query returns the hosts average\n-- memory usage and peaks over time.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    MEM_Usage AS \"Average Memory Usage\",\n    MEM_Peak AS \"Average Memory Peaks\"\nFROM \n    (\n        -- Hosts Max and Average Memory Usage Peaks\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage,\n            SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n        FROM\n            (\n                    SELECT history_datetime, memory_usage_percent, minutes_in_status, max_memory_usage, host_status, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, memory_usage_percent, minutes_in_status, max_memory_usage, host_status, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n        WHERE\n            -- Here we filter by active hosts only\n            hourly_daily.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND hourly_daily.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, MEM_Usage, MEM_Peak\nORDER BY sub_query.time\n"
    }
   ]
  },
  {
   "title": "Average CPU Usage and Peaks (over time) (BR2A)",
   "type": "graph",
   "description": "This report displays average CPU usage and peaks for a selected host over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the hosts\n-- CPU usage over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    CPU_Usage AS \"CPU Usage\"\nFROM \n    (\n        -- Here we get the hosts max and average CPU usage\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage\n        FROM v4_4_statistics_hosts_resources_usage_samples AS samples\n        WHERE\n            -- Here we filter by active hosts only\n            samples.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND samples.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, CPU_Usage\nORDER BY sub_query.time"
    },
    {
     "rawSql": "-- BR2A - This query returns the hourly and daily hosts\n-- CPU usage and peaks over time.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    CPU_Usage AS \"CPU Usage\",\n    CPU_Peak AS \"CPU Peak\"\nFROM \n    (\n        -- Here we get the hosts max and average CPU usage\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage,\n            SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n        FROM\n            (\n                    SELECT history_datetime, cpu_usage_percent, minutes_in_status, max_cpu_usage, host_status, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, cpu_usage_percent, minutes_in_status, max_cpu_usage, host_status, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n        WHERE\n            -- Here we filter by active hosts only\n            hourly_daily.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND hourly_daily.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, CPU_Usage, CPU_Peak\nORDER BY sub_query.time"
    }
   ]
  },
  {
   "title": "Average Number of Virtual Machines and Peaks (over time) (BR2A)",
   "type": "graph",
   "description": "This report displays average number of virtual machines and peaks for a selected host over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the hosts\n-- active VMs counts over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    CAST ( VMS AS int ) AS \"Number of Virtual Machines\"\nFROM \n    (\n        -- Here we get the hosts Max and average active vms counts\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS\n        FROM v4_4_statistics_hosts_resources_usage_samples AS samples\n        WHERE\n            -- Here we filter by active hosts only\n            samples.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND samples.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, VMS\nORDER BY sub_query.time"
    },
    {
     "rawSql": "-- BR2A - This query returns the hourly and daily hosts\n-- active VMs counts over time\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(sub_query.time),\n    CAST ( VMS AS int ) AS \"Avg. Number of Virtual Machines\",\n    CAST ( VMS_Peak AS int ) AS \"Avg. Peaks of Number of Virtual Machines\"\nFROM \n    (\n        -- Here we get the hosts Max and average active vms counts\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS,\n            SUM ( COALESCE ( max_active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS_Peak\n        FROM\n            (\n                    SELECT history_datetime, active_vms, minutes_in_status, max_active_vms, host_status, host_id \n                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, active_vms, minutes_in_status, max_active_vms, host_status, host_id\n                    FROM v4_4_statistics_hosts_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            )\n            ) AS hourly_daily\n        WHERE\n            -- Here we filter by active hosts only\n            hourly_daily.host_status = 1\n            -- Here we filter by the host chosen by the user\n            AND hourly_daily.host_id IN ($host_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY sub_query.time, VMS, VMS_Peak\nORDER BY sub_query.time"
    }
   ]
  },
  {
   "title": "Top 5 Busiest Ethernet Interface Tx and Rx Rates (over time) (BR2A)",
   "type": "graph",
   "description": "This report displays for the top 5 busiest Ethernet interfaces the average transmit and receive rates for a selected host over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns top 5 busiest\n-- Ethernet Interface Tx and Rx Rates, over time\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    $__time(all_sub_queries.time),\n    CONCAT \n    (\n        COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) || ' (', \n        COALESCE ( host_name, MAX ( host_name ) over ( partition BY 1 ), '' ) || ')'\n    ) AS interface_host_name,\n    AVG ( Rx_rate ) AS \"Avg. Rx\",\n    AVG ( Tx_rate ) AS \"Avg. Tx\"\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            CASE\n                WHEN v4_4_configuration_history_hosts_interfaces.delete_date IS NULL\n                    THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n            ||\n            '*'\n            END AS interface_name,\n            CASE\n                WHEN MAX (v4_4_configuration_history_hosts.delete_date) IS NULL\n                    THEN MAX (host_name)\n                ELSE MAX (host_name)\n            ||\n            '*'\n            END AS host_name,\n            statistics.history_datetime AS time,\n            AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate,\n            AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n        FROM\n            v4_4_statistics_hosts_interfaces_resources_usage_samples AS statistics\n            INNER JOIN v4_4_configuration_history_hosts_interfaces\n                ON \n                    (\n                        v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                        statistics.host_interface_id\n                    )\n            INNER JOIN v4_4_configuration_history_hosts\n                ON\n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        v4_4_configuration_history_hosts_interfaces.host_id\n                    )\n        WHERE\n            history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest host interfaces configuration\n            AND v4_4_configuration_history_hosts_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_hosts_interfaces AS a\n                        GROUP BY a.host_interface_id\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                IN \n                    (\n                        SELECT c.host_interface_id\n                        FROM \n                            v4_4_statistics_hosts_interfaces_resources_usage_samples AS b\n                            INNER JOIN v4_4_configuration_history_hosts_interfaces AS c\n                                ON \n                                    ( \n                                        c.host_interface_id = \n                                        b.host_interface_id \n                                    )\n                            INNER JOIN \n                            v4_4_statistics_hosts_resources_usage_samples AS samples\n                                ON \n                                    (\n                                        samples.host_configuration_version =\n                                        c.host_configuration_version\n                                        AND samples.history_datetime =\n                                        b.history_datetime\n                                    )\n                        WHERE\n                            -- Here we filter by active hosts only\n                            samples.host_status = 1\n                            AND c.host_id IN ($host_id)\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM v4_4_configuration_history_hosts_interfaces AS d\n                                        GROUP BY d.host_interface_id\n                                    )\n                            -- Here we get or remove deleted entities according to what the user chose\n                            -- in the \"show_deleted\" parameter.\n                            AND\n                                CASE\n                                    WHEN '$show_deleted'='Yes'\n                                        THEN 1=1\n                                    WHEN '$show_deleted'='No'\n                                        THEN v4_4_configuration_history_hosts_interfaces.delete_date isnull\n                                END\n                        GROUP BY c.host_interface_id\n                        ORDER BY\n                                AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                DESC\n                        LIMIT 5\n                    )\n            -- Here we get or remove deleted entities according to what the user chose\n            -- in the \"show_deleted\" parameter.\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_4_configuration_history_hosts_interfaces.delete_date isnull\n                END\n        GROUP BY\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            interface_name,\n            host_name,\n            statistics.history_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY all_sub_queries.time, interface_name, host_name\nORDER BY all_sub_queries.time ASC"
    },
    {
     "rawSql": "-- BR2A - This query returns top 5 busiest\n-- Ethernet Interface Tx and Rx Rates, over time\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    $__time(all_sub_queries.time),\n    CONCAT \n    (\n        COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) || ' (', \n        COALESCE ( host_name, MAX ( host_name ) over ( partition BY 1 ), '' ) || ')'\n    ) AS interface_host_name,\n    AVG ( Rx_rate ) AS \"Avg. Receive Rate\",\n    AVG ( Tx_rate ) AS \"Avg. Transmit Rate\"\nFROM \n    (\n        SELECT\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            CASE\n                WHEN v4_4_configuration_history_hosts_interfaces.delete_date IS NULL\n                    THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n            ||\n            '*'\n            END AS interface_name,\n            CASE\n                WHEN MAX (v4_4_configuration_history_hosts.delete_date) IS NULL\n                    THEN MAX (host_name)\n                ELSE MAX (host_name)\n            ||\n            '*'\n            END AS host_name,\n            statistics.history_datetime AS time,\n            AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate,\n            AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n        FROM\n            (\n                    SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent \n                    FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent \n                    FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                            )\n            ) AS statistics\n            INNER JOIN v4_4_configuration_history_hosts_interfaces\n                ON \n                    (\n                        v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                        statistics.host_interface_id\n                    )\n            INNER JOIN v4_4_configuration_history_hosts\n                ON\n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        v4_4_configuration_history_hosts_interfaces.host_id\n                    )\n        WHERE\n            history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we filter by the host chosen by the user\n            AND v4_4_configuration_history_hosts_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_hosts_interfaces AS a\n                        GROUP BY a.host_interface_id\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_hosts_interfaces AS a\n                        GROUP BY a.host_interface_id\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                IN \n                    (\n                        SELECT c.host_interface_id\n                        FROM\n                            (\n                                    SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                    FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                UNION\n                                    SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                    FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                                    WHERE\n                                        history_datetime <\n                                            (\n                                                SELECT MIN ( history_datetime )\n                                                FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                            )\n                            ) AS b\n                            INNER JOIN v4_4_configuration_history_hosts_interfaces c\n                                ON \n                                    ( \n                                        c.host_interface_id = \n                                        b.host_interface_id \n                                    )\n                            INNER JOIN \n                            (\n                                    SELECT history_datetime, host_id, host_status, host_configuration_version \n                                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                                UNION\n                                    SELECT history_datetime, host_id, host_status, host_configuration_version \n                                    FROM v4_4_statistics_hosts_resources_usage_daily\n                                    WHERE\n                                        history_datetime <\n                                            (\n                                                SELECT MIN ( history_datetime )\n                                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                                            )\n                            ) AS hourly_daily\n                                ON \n                                    (\n                                        hourly_daily.host_configuration_version =\n                                        c.host_configuration_version\n                                        AND hourly_daily.history_datetime =\n                                        b.history_datetime\n                                    )\n                        WHERE\n                            -- Here we filter by active hosts only\n                            hourly_daily.host_status = 1\n                            AND c.host_id IN ($host_id)\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM v4_4_configuration_history_hosts_interfaces AS d\n                                        GROUP BY d.host_interface_id\n                                    )\n                            -- Here we get or remove deleted entities according to what the user chose\n                            -- in the \"show_deleted\" parameter.\n                            AND\n                                CASE\n                                    WHEN '$show_deleted'='Yes'\n                                        THEN 1=1\n                                    WHEN '$show_deleted'='No'\n                                        THEN v4_4_configuration_history_hosts_interfaces.delete_date isnull\n                                END\n                        GROUP BY c.host_interface_id\n                        ORDER BY\n                                AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                DESC\n                        LIMIT 5\n                    )\n            -- Here we get or remove deleted entities according to what the user chose\n            -- in the \"show_deleted\" parameter.\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN v4_4_configuration_history_hosts_interfaces.delete_date isnull\n                END\n        GROUP BY\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            interface_name,\n            host_name,\n            statistics.history_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY all_sub_queries.time, interface_name, host_name\nORDER BY all_sub_queries.time ASC"
    }
   ]
  },
  {
   "title": "Top 5 Ethernet Interface Tx and Rx Dropped Packets (over time) (BR2A)",
   "type": "graph",
   "description": "Average transmitted and received total dropped packets of the host interfaces, over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the Ethernet Interface \n-- average Tx and Rx total dropped packets, over time.\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\nSELECT DISTINCT\n    time,\n    CONCAT \n    (\n        COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) || ' (', \n        COALESCE ( host_name, MAX ( host_name ) over ( partition BY 1 ), '' ) || ')'\n    ) AS interface_host_name,\n    AVG ( Rx_drop ) AS \"Rx. Drop\",\n    AVG ( Tx_drop ) AS \"Tx. Drop\"\nFROM \n    (\n        SELECT DISTINCT\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            CASE\n                WHEN v4_4_configuration_history_hosts_interfaces.delete_date IS NULL\n                    THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n            ||\n            '*'\n            END AS interface_name,\n            CASE\n                WHEN MAX (v4_4_configuration_history_hosts.delete_date) IS NULL\n                    THEN MAX (host_name)\n                ELSE MAX (host_name)\n            ||\n            '*'\n            END AS host_name,\n            statistics.history_datetime AS time,\n            AVG ( COALESCE ( received_dropped_total_packets, 0 ) ) AS Rx_drop,\n            AVG ( COALESCE ( transmitted_dropped_total_packets, 0 ) ) AS Tx_drop\n        FROM\n            (\n                SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets \n                FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n            ) AS statistics\n            INNER JOIN \n            v4_4_configuration_history_hosts_interfaces\n                ON \n                    (\n                        v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                        statistics.host_interface_id\n                    )\n            INNER JOIN \n            v4_4_configuration_history_hosts\n                ON\n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        v4_4_configuration_history_hosts_interfaces.host_id\n                    )\n        WHERE\n            -- Here we filter by the host chosen by the user\n            v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n            -- Here we filter by the time range chosen by the user\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            AND v4_4_configuration_history_hosts_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_hosts_interfaces AS a\n                        GROUP BY a.host_interface_id\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id\n                IN \n                    (\n                        SELECT host_interface_id\n                        FROM v4_4_latest_configuration_hosts_interfaces\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                IN \n                    (\n                        SELECT c.host_interface_id\n                        FROM\n                            (\n                                SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets\n                                FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n                            ) AS b\n                            INNER JOIN \n                            v4_4_configuration_history_hosts_interfaces c\n                                ON \n                                    ( \n                                        c.host_interface_id = \n                                        b.host_interface_id \n                                    )\n                            INNER JOIN \n                            (\n                                SELECT history_datetime, host_id, host_status \n                                FROM v4_4_statistics_hosts_resources_usage_samples\n                            ) AS samples_hourly_daily\n                                ON \n                                    (\n                                        samples_hourly_daily.history_datetime =\n                                        b.history_datetime \n                                        AND samples_hourly_daily.host_id IN ($host_id)\n                                    )\n                        WHERE\n                            -- Here we filter by active host only\n                            samples_hourly_daily.host_status = 1\n                            AND c.host_id IN ($host_id)\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM v4_4_configuration_history_hosts_interfaces AS d\n                                        GROUP BY d.host_interface_id\n                                    )\n                        GROUP BY c.host_interface_id\n                        ORDER BY\n                                AVG ( COALESCE ( b.received_dropped_total_packets, 0 ) ) +\n                                AVG ( COALESCE ( b.transmitted_dropped_total_packets, 0 ) ) \n                                DESC\n                                LIMIT 5\n                    )\n        GROUP BY\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            interface_name,\n            host_name,\n            statistics.history_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is up to 24 hours back \nWHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY \n    all_sub_queries.time, \n    interface_name,\n    host_name\nORDER BY all_sub_queries.time ASC"
    },
    {
     "rawSql": "-- BR2A - This query returns the Ethernet Interface \n-- average Tx and Rx total dropped packets, over time.\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\nSELECT DISTINCT\n    time,\n    CONCAT \n    (\n        COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) || ' (', \n        COALESCE ( host_name, MAX ( host_name ) over ( partition BY 1 ), '' ) || ')'\n    ) AS interface_host_name,\n    AVG ( Rx_drop ) AS \"Rx. Drop\",\n    AVG ( Tx_drop ) AS \"Tx. Drop\"\nFROM \n    (\n        SELECT DISTINCT\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            CASE\n                WHEN v4_4_configuration_history_hosts_interfaces.delete_date IS NULL\n                    THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n            ||\n            '*'\n            END AS interface_name,\n            CASE\n                WHEN MAX (v4_4_configuration_history_hosts.delete_date) IS NULL\n                    THEN MAX (host_name)\n                ELSE MAX (host_name)\n            ||\n            '*'\n            END AS host_name,\n            statistics.history_datetime AS time,\n            AVG ( COALESCE ( received_dropped_total_packets, 0 ) ) AS Rx_drop,\n            AVG ( COALESCE ( transmitted_dropped_total_packets, 0 ) ) AS Tx_drop\n        FROM\n            (\n                    SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets \n                    FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                UNION\n                    SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets \n                    FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                    WHERE\n                        history_datetime <\n                            (\n                                SELECT MIN ( history_datetime )\n                                FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                            )\n            ) AS statistics\n            INNER JOIN \n            v4_4_configuration_history_hosts_interfaces\n                ON \n                    (\n                        v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                        statistics.host_interface_id\n                    )\n            INNER JOIN \n            v4_4_configuration_history_hosts\n                ON\n                    (\n                        v4_4_configuration_history_hosts.host_id =\n                        v4_4_configuration_history_hosts_interfaces.host_id\n                    )\n        WHERE\n            -- Here we filter by the host chosen by the user\n            v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n            -- Here we filter by the time range chosen by the user\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            AND v4_4_configuration_history_hosts_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_4_configuration_history_hosts_interfaces AS a\n                        GROUP BY a.host_interface_id\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id\n                IN \n                    (\n                        SELECT host_interface_id\n                        FROM v4_4_latest_configuration_hosts_interfaces\n                    )\n            AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                IN \n                    (\n                        SELECT c.host_interface_id\n                        FROM\n                            (\n                                    SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets\n                                    FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                UNION\n                                    SELECT history_datetime, host_interface_id, received_dropped_total_packets, transmitted_dropped_total_packets\n                                    FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                                    WHERE\n                                        history_datetime <\n                                            (\n                                                SELECT MIN ( history_datetime )\n                                                FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                            )\n                            ) AS b\n                            INNER JOIN \n                            v4_4_configuration_history_hosts_interfaces c\n                                ON \n                                    ( \n                                        c.host_interface_id = \n                                        b.host_interface_id \n                                    )\n                            INNER JOIN \n                            (\n                                    SELECT history_datetime, host_id, host_status \n                                    FROM v4_4_statistics_hosts_resources_usage_hourly\n                                UNION\n                                    SELECT history_datetime, host_id, host_status \n                                    FROM v4_4_statistics_hosts_resources_usage_daily\n                                    WHERE\n                                        history_datetime <\n                                            (\n                                                SELECT MIN ( history_datetime )\n                                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                                            )\n                            ) AS samples_hourly_daily\n                                ON \n                                    (\n                                        samples_hourly_daily.history_datetime =\n                                        b.history_datetime \n                                        AND samples_hourly_daily.host_id IN ($host_id)\n                                    )\n                        WHERE\n                            -- Here we filter by active host only\n                            samples_hourly_daily.host_status = 1\n                            AND c.host_id IN ($host_id)\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM v4_4_configuration_history_hosts_interfaces AS d\n                                        GROUP BY d.host_interface_id\n                                    )\n                        GROUP BY c.host_interface_id\n                        ORDER BY\n                                AVG ( COALESCE ( b.received_dropped_total_packets, 0 ) ) +\n                                AVG ( COALESCE ( b.transmitted_dropped_total_packets, 0 ) ) \n                                DESC\n                                LIMIT 5\n                    )\n        GROUP BY\n            v4_4_configuration_history_hosts_interfaces.host_interface_id,\n            interface_name,\n            host_name,\n            statistics.history_datetime\n    ) AS all_sub_queries\n-- Show data only when the selected period is more then 24 hours back\nWHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\nGROUP BY \n    all_sub_queries.time, \n    interface_name,\n    host_name\nORDER BY all_sub_queries.time ASC"
    }
   ]
  }
 ]
}