{
 "title": "Hosts Resource Usage Dashboard",
 "description": "The hosts resource usage dashboard displaying resources usage measurements - number of virtual machines, CPU, memory, and network Tx/Rx",
 "tags": [
  "Host",
  "Cluster",
  "CPU",
  "Memory",
  "Interface"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" },
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT   CAST ( datacenter_id AS varchar ) AS __value,  CASE          WHEN delete_date IS NULL  \t     \t    THEN datacenter_name \t \tWHEN delete_date IS NOT null  \t      \t    THEN datacenter_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  END AS __text  \t\tFROM v4_4_configuration_history_datacenters  \t\tWHERE       \t\t    history_id           \t\t\t    IN               \t\t\t\t(  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_datacenters a  \t\t         \t\t\t\t\tGROUP BY a.datacenter_id \t         \t\t\t\t) \t \t\t\tAND datacenter_id  \t         \t\t\t    IN \t\t\t     \t\t\t\t    ( \t\t\t\t\t \t\t\t\t\t\tSELECT DISTINCT datacenter_id \t\t\t\t\t \t\t\t\t\t\tFROM v4_4_configuration_history_clusters \t\t\t\t\t \t\t\t\t\t\tWHERE  \t\t\t\t\t     \t\t\t\t\t\t    cluster_id \t\t\t\t\t         \t\t\t\t\t\t        IN \t\t\t\t\t             \t\t\t\t\t\t            ( \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tSELECT DISTINCT cluster_id \t\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t\tFROM v4_4_configuration_history_hosts  \t\t\t\t\t\t\t\t \t\t\t\t\t\t\t\t\t) \t\t\t\t\t) \t\t\tAND \t    \t\t\t    CASE  \t        \t\t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    THEN 1=1 \t\t    \t\t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    THEN v4_4_configuration_history_datacenters.delete_date ISNULL \t                END  \t\t"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT        CAST ( cluster_id AS varchar ) AS __value,  \tCASE      \t    WHEN delete_date IS NULL  \t     \t\t    THEN cluster_name \t \t\tWHEN delete_date IS NOT null  \t      \t\t    THEN cluster_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  \tEND AS __text  \tFROM v4_4_configuration_history_clusters  \tWHERE       \t    history_id           \t\t    IN               \t\t\t    (  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_clusters a  \t\t         \t\t\t\t\tGROUP BY a.cluster_id \t         \t\t\t\t) \t \t\tAND cluster_id  \t\t    IN \t\t\t     \t\t\t    ( \t\t\t\t\t \t\t\t        SELECT DISTINCT cluster_id \t\t\t\t\t \t\t\t\t\tFROM v4_4_configuration_history_hosts \t\t\t\t \t\t\t\t) \t\tAND \t    \t\t    CASE  \t        \t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t    THEN 1=1 \t\t    \t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t    THEN v4_4_configuration_history_clusters.delete_date ISNULL \t    \t\t\tEND     \t\tAND datacenter_id IN ($datacenter_id)  \t\t"
   },
   {
    "name": "host_id",
    "label": "Host",
    "query": "SELECT DISTINCT   CAST ( host_id AS varchar ) AS __value,  CASE          WHEN delete_date IS NULL  \t     \t    THEN host_name \t \tWHEN delete_date IS NOT null  \t      \t    THEN host_name || ' (Removed on ' || CAST ( CAST ( delete_date AS date ) AS varchar ) || ')'  END AS __text  \t\tFROM v4_4_configuration_history_hosts  \t\tWHERE       \t\t    history_id           \t\t\t    IN               \t\t\t\t(  \t             \t\t\t\t\tSELECT MAX ( a.history_id )  \t\t         \t\t\t\t\tFROM v4_4_configuration_history_hosts a  \t\t         \t\t\t\t\tGROUP BY a.host_id \t         \t\t\t\t) \t \t\t\tAND cluster_id IN ($cluster_id)  \t\t\tAND \t    \t\t\t    CASE  \t        \t\t\t\t    WHEN '$show_deleted'='Yes' \t            \t\t\t\t\t    THEN 1=1 \t\t    \t\t\t\t\tWHEN '$show_deleted'='No' \t\t        \t\t\t\t\t    THEN v4_4_configuration_history_hosts.delete_date ISNULL \t                END  \t\t"
   },
   {
    "name": "period_id",
    "label": "Period",
    "query": "SELECT 'Day of Week' AS __text, 1 AS __value UNION SELECT  'Hour of Day' AS  __text, 2 AS __value"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "\n###### This dashboard displays resource usage (number of virtual machines, CPU, memory, network Tx/Rx) for a selected host within a selected period.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Number of Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Average Number of Virtual Machines (BR2C)",
   "type": "graph",
   "description": "This report displays average number of virtual machines for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average active VMs counts by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Average active vms\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    vms_num AS \"Avg. Number of VMs\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( VMS ) AS \"vms_num\"\n        FROM \n            (\n                -- Here we get the hosts active vms\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS\n                FROM\n                        (\n                            SELECT history_datetime, active_vms, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')\n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average active VMs counts by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Average active vms\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    vms_num AS \"Avg. Number of VMs\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( VMS ) AS \"vms_num\"\n        FROM \n            (\n                -- Here we get the hosts active vms\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS\n                FROM\n                        (\n                                SELECT history_datetime, active_vms, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, active_vms, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Average Number of Virtual Machine Peaks (BR2C)",
   "type": "graph",
   "description": "This report displays average number of virtual machines peaks for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average active VMs counts by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Max active vms\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    vms_peak AS \"Avg. VMs Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( VMS_Peak ) AS vms_peak\n        FROM \n            (\n                -- Here we get the hosts max active vms\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS_Peak\n                FROM\n                        (\n                            SELECT history_datetime, active_vms AS max_active_vms, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average active VMs counts by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Max active vms\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    vms_peak AS \"Avg. VMs Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( VMS_Peak ) AS vms_peak\n        FROM \n            (\n                -- Here we get the hosts max active vms\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_active_vms, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS VMS_Peak\n                FROM\n                        (\n                                SELECT history_datetime, max_active_vms, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, max_active_vms, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  { "title": "Host CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average CPU Usage (BR2C)",
   "type": "graph",
   "description": "This report displays average CPU usage for a selected host within a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average CPU usage peaks by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Average CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    cpu_usage AS \"CPU Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( CPU_Usage ) AS cpu_usage\n        FROM \n            (\n                -- Here we get the hosts CPU usage percent\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage\n                FROM\n                        (\n                            SELECT history_datetime, cpu_usage_percent, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n         -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')       \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average CPU usage peaks by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Average CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    cpu_usage AS \"CPU Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( CPU_Usage ) AS cpu_usage\n        FROM \n            (\n                -- Here we get the hosts CPU usage percent\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage\n                FROM\n                        (\n                                SELECT history_datetime, cpu_usage_percent, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, cpu_usage_percent, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Average CPU Usage Peaks (BR2C)",
   "type": "graph",
   "description": "This report displays average CPU usage peaks for a selected host within a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average CPU usage peaks by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Max CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    cpu_peak AS \"CPU Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( CPU_Peak ) AS cpu_peak\n        FROM \n            (\n                -- Here we get the hosts max CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n                FROM\n                        (\n                            SELECT history_datetime, cpu_usage_percent AS max_cpu_usage, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average CPU usage peaks by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Max CPU usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    cpu_peak AS \"CPU Peak\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( CPU_Peak ) AS cpu_peak\n        FROM \n            (\n                -- Here we get the hosts max CPU usage \n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n                FROM\n                        (\n                                SELECT history_datetime, max_cpu_usage, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, max_cpu_usage, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  { "title": "Host Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Average Memory Usage (BR2C)",
   "type": "graph",
   "description": "This report displays average memory usage for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average memory usage peaks by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Average memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    mem_usage AS \"Memory Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( MEM_Usage ) AS mem_usage\n        FROM \n            (\n                -- Here we get the hosts memory usage percent\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage\n                FROM\n                        (\n                            SELECT history_datetime, memory_usage_percent, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average memory usage peaks by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Average memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    mem_usage AS \"Memory Usage\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( MEM_Usage ) AS mem_usage\n        FROM \n            (\n                -- Here we get the hosts memory usage percent\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage\n                FROM\n                        (\n                                SELECT history_datetime, memory_usage_percent, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, memory_usage_percent, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')\n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  {
   "title": "Average Memory Usage Peaks (BR2C)",
   "type": "graph",
   "description": "This report displays average memory usage peaks for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average memory usage peaks by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Max memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    mem_peak AS \"Memory Usage Peaks\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( MEM_Peak ) AS mem_peak\n        FROM \n            (\n                -- Here we get the hosts max memory usage\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n                FROM\n                        (\n                            SELECT history_datetime, memory_usage_percent AS max_memory_usage, minutes_in_status, host_status, host_id\n                            FROM v4_4_statistics_hosts_resources_usage_samples\n                        ) AS samples\n                WHERE\n                    -- Here we filter by active hosts only\n                    samples.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND samples.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    },
    {
     "rawSql": "-- BR2C - This query returns the hosts\n-- max and average memory usage peaks by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Max memory usage\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n    mem_peak AS \"Memory Usage Peaks\"\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n            AVG ( MEM_Peak ) AS mem_peak\n        FROM \n            (\n                -- Here we get the hosts max memory usage\n                SELECT\n                    history_datetime AS time,\n                    SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n                    SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n                FROM\n                        (\n                                SELECT history_datetime, max_memory_usage, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_hourly\n                            UNION\n                                SELECT history_datetime, max_memory_usage, minutes_in_status, host_status, host_id\n                                FROM v4_4_statistics_hosts_resources_usage_daily\n                                WHERE\n                                    history_datetime <\n                                        (\n                                            SELECT MIN ( history_datetime )\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        )\n                        ) AS hourly_daily\n                WHERE\n                    -- Here we filter by active hosts only\n                    hourly_daily.host_status = 1\n                    -- Here we filter by the host chosen by the user\n                    AND hourly_daily.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                GROUP BY history_datetime\n            ) AS sub_query\n         -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')       \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries "
    }
   ]
  },
  { "title": "Host Interface Rx and Tx Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Top 3 Most Utilized Network Interface - Transmit Rate (BR2C)",
   "type": "graph",
   "description": "This report displays for the top 3 most utilized network interfaces the average network interface transmit rate for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- ethernet interface Tx and Rx rates, by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Tx rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n        Tx_rate\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n        AVG ( Tx_rate ) AS Tx_rate\n        FROM \n            (\n                SELECT\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                        ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    statistics.history_datetime AS time,\n                    AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n                FROM\n                    (\n                        SELECT history_datetime, host_interface_id, transmit_rate_percent\n                        FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n                    ) AS statistics\n                    INNER JOIN v4_4_configuration_history_hosts_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                                statistics.host_interface_id\n                            )\n                WHERE\n                    -- Here we filter by the host chosen by the user\n                    v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    AND v4_4_configuration_history_hosts_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_hosts_interfaces AS a\n                                GROUP BY a.host_interface_id\n                            )\n                    AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                        IN \n                            (\n                                SELECT c.host_interface_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_hosts_interfaces c\n                                        ON \n                                            ( \n                                                c.host_interface_id = \n                                                b.host_interface_id \n                                            )\n                                    INNER JOIN\n                                    (\n                                        SELECT history_datetime, host_id, host_status\n                                        FROM v4_4_statistics_hosts_resources_usage_samples\n                                    ) AS e\n                                        ON \n                                            (\n                                                e.history_datetime = b.history_datetime\n                                                AND e.host_id IN ($host_id)\n                                            )\n                                WHERE\n                                    -- Here we filter by active hosts only\n                                    e.host_status = 1\n                                    AND c.host_id IN ($host_id)\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM v4_4_configuration_history_hosts_interfaces AS d\n                                                GROUP BY d.host_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.host_interface_id\n                                ORDER BY\n                                        AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                        AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                        DESC\n                                LIMIT 3\n                            ) \n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    interface_name,\n                    statistics.history_datetime\n            ) AS from_sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES')         \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- ethernet interface Tx and Rx rates, by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Tx rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n        Tx_rate\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n        AVG ( Tx_rate ) AS Tx_rate\n        FROM \n            (\n                SELECT\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                        ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    statistics.history_datetime AS time,\n                    AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n                FROM\n                    (\n                            SELECT history_datetime, host_interface_id, transmit_rate_percent\n                            FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, host_interface_id, transmit_rate_percent\n                            FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                    )\n                    ) AS statistics\n                    INNER JOIN v4_4_configuration_history_hosts_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                                statistics.host_interface_id\n                            )\n                WHERE\n                    -- Here we filter by the host chosen by the user\n                    v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    AND v4_4_configuration_history_hosts_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_hosts_interfaces AS a\n                                GROUP BY a.host_interface_id\n                            )\n                    AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                        IN \n                            (\n                                SELECT c.host_interface_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_hosts_interfaces c\n                                        ON \n                                            ( \n                                                c.host_interface_id = \n                                                b.host_interface_id \n                                            )\n                                    INNER JOIN\n                                    (\n                                            SELECT history_datetime, host_id, host_status\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, host_id, host_status\n                                            FROM v4_4_statistics_hosts_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_hosts_resources_usage_hourly\n                                                    )\n                                    ) AS e\n                                        ON \n                                            (\n                                                e.history_datetime = b.history_datetime\n                                                AND e.host_id IN ($host_id)\n                                            )\n                                WHERE\n                                    -- Here we filter by active hosts only\n                                    e.host_status = 1\n                                    AND c.host_id IN ($host_id)\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM v4_4_configuration_history_hosts_interfaces AS d\n                                                GROUP BY d.host_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.host_interface_id\n                                ORDER BY\n                                        AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                        AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                        DESC\n                                LIMIT 3\n                            ) \n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    interface_name,\n                    statistics.history_datetime\n            ) AS from_sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries"
    }
   ]
  },
  {
   "title": "Top 3 Most Utilized Network Interface - Receive Rate (BR2C)",
   "type": "graph",
   "description": "This report displays for the top 3 most utilized network interfaces the average network interface receive rate for a selected host within a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- ethernet interface Tx and Rx rates, by hour of day and day of week\n\n-- This query (A) displays recent data from the last hours, \n-- and for each minute, using the samples table.\n\n-- Rx rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n        Rx_rate\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n        AVG ( Rx_rate ) AS Rx_rate\n        FROM \n            (\n                SELECT\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                        ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    statistics.history_datetime AS time,\n                    AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate\n                FROM\n                    (\n                        SELECT history_datetime, host_interface_id, receive_rate_percent\n                        FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n                    ) AS statistics\n                    INNER JOIN v4_4_configuration_history_hosts_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                                statistics.host_interface_id\n                            )\n                WHERE\n                    -- Here we filter by the host chosen by the user\n                    v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    AND v4_4_configuration_history_hosts_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_hosts_interfaces AS a\n                                GROUP BY a.host_interface_id\n                            )\n                    AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                        IN \n                            (\n                                SELECT c.host_interface_id\n                                FROM\n                                    (\n                                        SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_samples\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_hosts_interfaces c\n                                        ON \n                                            ( \n                                                c.host_interface_id = \n                                                b.host_interface_id \n                                            )\n                                    INNER JOIN\n                                    (\n                                        SELECT history_datetime, host_id, host_status\n                                        FROM v4_4_statistics_hosts_resources_usage_samples\n                                    ) AS e\n                                        ON \n                                            (\n                                                e.history_datetime = b.history_datetime\n                                                AND e.host_id IN ($host_id)\n                                            )\n                                WHERE\n                                    -- Here we filter by active hosts only\n                                    e.host_status = 1\n                                    AND c.host_id IN ($host_id)\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM v4_4_configuration_history_hosts_interfaces AS d\n                                                GROUP BY d.host_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.host_interface_id\n                                ORDER BY\n                                        AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                        AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                        DESC\n                                LIMIT 3\n                            ) \n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    interface_name,\n                    statistics.history_datetime\n            ) AS from_sub_query\n        -- Show data only when the selected period is up to 24 hours back \n        WHERE $__timeFrom() >= (NOW() - INTERVAL '1443 MINUTES') \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries"
    },
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- ethernet interface Tx and Rx rates, by hour of day and day of week\n\n-- This query (B) displays historical and recent data \n-- excluding the last few hours, by using the hourly and daily tables.\n\n-- Rx rate\nSELECT\n    NOW () AS time,\n    CASE $period_id\n        WHEN 1 \n            THEN \n                CASE CAST (num AS int)\n                    WHEN 1 \n                        THEN 'Sunday'\n                    WHEN 2 \n                        THEN 'Monday'\n                    WHEN 3 \n                        THEN 'Tuesday'\n                    WHEN 4 \n                        THEN 'Wednesday'\n                    WHEN 5 \n                        THEN'Thursday'\n                    WHEN 6 \n                        THEN 'Friday'\n                    WHEN 7 \n                        THEN 'Saturday'\n                END\n        WHEN 2 \n            THEN num\n    END AS num,\n        Rx_rate\nFROM \n    (\n        SELECT DISTINCT\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END AS num,\n        AVG ( Rx_rate ) AS Rx_rate\n        FROM \n            (\n                SELECT\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    CASE\n                        WHEN delete_date IS NULL\n                            THEN v4_4_configuration_history_hosts_interfaces.host_interface_name\n                        ELSE v4_4_configuration_history_hosts_interfaces.host_interface_name\n                    ||\n                    '*'\n                    END AS interface_name,\n                    statistics.history_datetime AS time,\n                    AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate\n                FROM\n                    (\n                            SELECT history_datetime, host_interface_id, receive_rate_percent\n                            FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                        UNION\n                            SELECT history_datetime, host_interface_id, receive_rate_percent\n                            FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                            WHERE\n                                history_datetime <\n                                    (\n                                        SELECT MIN ( history_datetime )\n                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                    )\n                    ) AS statistics\n                    INNER JOIN v4_4_configuration_history_hosts_interfaces\n                        ON \n                            (\n                                v4_4_configuration_history_hosts_interfaces.host_interface_id =\n                                statistics.host_interface_id\n                            )\n                WHERE\n                    -- Here we filter by the host chosen by the user\n                    v4_4_configuration_history_hosts_interfaces.host_id IN ($host_id)\n                    AND history_datetime >= $__timeFrom()\n                    AND history_datetime < $__timeTo()\n                    AND v4_4_configuration_history_hosts_interfaces.history_id \n                        IN \n                            (\n                                SELECT MAX ( a.history_id )\n                                FROM v4_4_configuration_history_hosts_interfaces AS a\n                                GROUP BY a.host_interface_id\n                            )\n                    AND v4_4_configuration_history_hosts_interfaces.host_interface_id \n                        IN \n                            (\n                                SELECT c.host_interface_id\n                                FROM\n                                    (\n                                            SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, host_interface_id, receive_rate_percent, transmit_rate_percent\n                                            FROM v4_4_statistics_hosts_interfaces_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_hosts_interfaces_resources_usage_hourly\n                                                    )\n                                    ) AS b\n                                    INNER JOIN v4_4_configuration_history_hosts_interfaces c\n                                        ON \n                                            ( \n                                                c.host_interface_id = \n                                                b.host_interface_id \n                                            )\n                                    INNER JOIN\n                                    (\n                                            SELECT history_datetime, host_id, host_status\n                                            FROM v4_4_statistics_hosts_resources_usage_hourly\n                                        UNION\n                                            SELECT history_datetime, host_id, host_status\n                                            FROM v4_4_statistics_hosts_resources_usage_daily\n                                            WHERE\n                                                history_datetime <\n                                                    (\n                                                        SELECT MIN ( history_datetime )\n                                                        FROM v4_4_statistics_hosts_resources_usage_hourly\n                                                    )\n                                    ) AS e\n                                        ON \n                                            (\n                                                e.history_datetime = b.history_datetime\n                                                AND e.host_id IN ($host_id)\n                                            )\n                                WHERE\n                                    -- Here we filter by active hosts only\n                                    e.host_status = 1\n                                    AND c.host_id IN ($host_id)\n                                    AND b.history_datetime >= $__timeFrom()\n                                    AND b.history_datetime < $__timeTo()\n                                    AND c.history_id \n                                        IN \n                                            (\n                                                SELECT MAX ( d.history_id )\n                                                FROM v4_4_configuration_history_hosts_interfaces AS d\n                                                GROUP BY d.host_interface_id\n                                            )\n                                    -- Here we get or remove deleted VM devices according to what the user chose\n                                    -- in the \"show_deleted\" parameter\n                                    AND\n                                        CASE\n                                            WHEN '$show_deleted'='Yes'\n                                                THEN 1=1\n                                            WHEN '$show_deleted'='No'\n                                                THEN delete_date isnull\n                                        END\n                                GROUP BY c.host_interface_id\n                                ORDER BY\n                                        AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                                        AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                                        DESC\n                                LIMIT 3\n                            ) \n                    -- Here we get or remove deleted VM devices according to what the user chose\n                    -- in the \"show_deleted\" parameter\n                    AND\n                        CASE\n                            WHEN '$show_deleted'='Yes'\n                                THEN 1=1\n                            WHEN '$show_deleted'='No'\n                                THEN delete_date isnull\n                        END\n                GROUP BY\n                    v4_4_configuration_history_hosts_interfaces.host_interface_id,\n                    interface_name,\n                    statistics.history_datetime\n            ) AS from_sub_query\n        -- Show data only when the selected period is more then 24 hours back\n        WHERE $__timeFrom() < (NOW() - INTERVAL '1443 MINUTES')        \n        GROUP BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END\n        ORDER BY\n            CASE $period_id\n                WHEN 1\n                    THEN TO_CHAR (time, 'D')\n                WHEN 2\n                    THEN TO_CHAR (time, 'HH24:00') \n            END ASC\n    ) AS all_sub_queries"
    }
   ]
  }
 ]
}