{
 "title": "Single Host Trend Dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name AS __text , datacenter_id AS __value FROM v4_3_configuration_history_datacenters "
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT cluster_name AS __text, cluster_id AS __value FROM v4_3_configuration_history_clusters WHERE datacenter_id IN  ('$datacenter_id')"
   },
   {
    "name": "host_id",
    "label": "Host",
    "query": "SELECT DISTINCT host_name AS __text , host_id AS __value FROM v4_3_configuration_history_hosts WHERE cluster_id IN ('$cluster_id')"
   },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" }
  ]
 },
 "panels": [
  {
   "title": "Average Memory Usage and Peaks(Over Time) (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the daily hosts\n-- Memory and Usage Peaks over time.\n\nSELECT DISTINCT\n    $__time(a.time),\n    MEM_Usage AS \"Average Memory Usage\",\n    MEM_Peak AS \"Average Memory Peaks\"\nFROM (\n    -- Hosts Max and Average Memory Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                memory_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Usage,\n        SUM (\n            COALESCE (\n                max_memory_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Peak\n    FROM\n        (\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n             UNION\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n        ) AS hourly_daily\n    WHERE\n        -- Here we filter by active hosts only\n        hourly_daily.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND hourly_daily.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    a.time,\n    MEM_Usage,\n    MEM_Peak\nORDER BY\n    a.time\n"
    }
   ]
  },
  {
   "title": "Average CPU Usage and Peaks(Over Time) (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the hourly and daily hosts\n-- CPU Usage and Peaks over time\n\nSELECT DISTINCT\n    $__time(a.time),\n    CPU_Usage,\n    CPU_Peak\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                cpu_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Usage,\n        SUM (\n            COALESCE (\n                max_cpu_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Peak\n    FROM\n        (\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n             UNION\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n        ) AS hourly_daily\n    WHERE\n        -- Here we filter by active hosts only\n        hourly_daily.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND hourly_daily.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    a.time,\n    CPU_Usage,\n    CPU_Peak\nORDER BY\n   a.time"
    }
   ]
  },
  {
   "title": "Top 5 Busiest Ethernet Interface Tx and Rx Rates (Over Time) (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns top 5 busiest\n-- Ethernet Interface Tx and Rx Rates, over time\n\nSELECT DISTINCT\n    $__time(a.time),\n    COALESCE (\n        interface_name,\n        MAX ( interface_name ) over ( partition by 1 ),\n        ''\n    ) AS interface_name,\n    Rx_rate AS \"Avg. Receive Rate\",\n    Tx_rate AS \"Avg. Transmite Rate\"\nFROM (\n    SELECT\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        CASE\n            WHEN delete_date IS NULL\n                THEN\n                    v4_3_configuration_history_hosts_interfaces.host_interface_name\n            ELSE\n                v4_3_configuration_history_hosts_interfaces.host_interface_name\n                ||\n                '*'\n        END AS interface_name,\n        statistics.history_datetime AS time,\n        AVG (\n            COALESCE ( receive_rate_percent, 0 )\n        ) AS Rx_rate,\n        AVG (\n            COALESCE ( transmit_rate_percent, 0 )\n        ) AS Tx_rate\n    FROM\n        (\n             SELECT * FROM v4_3_statistics_hosts_interfaces_resources_usage_hourly\n             UNION\n             SELECT * FROM v4_3_statistics_hosts_interfaces_resources_usage_daily\n        ) AS statistics\n        INNER JOIN v4_3_configuration_history_hosts_interfaces\n            ON (\n                v4_3_configuration_history_hosts_interfaces.host_interface_id =\n                statistics.host_interface_id\n            )\n    WHERE\n        -- Here we filter by the host chosen by the user\n        v4_3_configuration_history_hosts_interfaces.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n        AND v4_3_configuration_history_hosts_interfaces.history_id IN (\n            SELECT MAX ( a.history_id )\n            FROM v4_3_configuration_history_hosts_interfaces AS a\n            GROUP BY a.host_interface_id\n        )\n        AND v4_3_configuration_history_hosts_interfaces.history_id IN (\n            SELECT MAX ( a.history_id )\n            FROM v4_3_configuration_history_hosts_interfaces AS a\n            GROUP BY a.host_interface_id\n        )\n        AND v4_3_configuration_history_hosts_interfaces.host_interface_id IN (\n            SELECT c.host_interface_id\n            FROM\n                (\n                    SELECT * FROM v4_3_statistics_hosts_interfaces_resources_usage_hourly\n                    UNION\n                    SELECT * FROM v4_3_statistics_hosts_interfaces_resources_usage_daily\n                ) AS b\n                INNER JOIN v4_3_configuration_history_hosts_interfaces c\n                    ON ( c.host_interface_id = b.host_interface_id )\n                INNER JOIN \n                            (\n                                 SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n                                 UNION\n                                 SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n                            ) AS hourly_daily\n                    ON (\n                        hourly_daily.history_datetime =\n                        b.history_datetime AND\n                        hourly_daily.host_id in ($host_id)\n                    )\n            WHERE\n                -- Here we filter by active hosts only\n                hourly_daily.host_status = 1\n                AND c.host_id in ($host_id)\n                AND c.history_id IN (\n                    SELECT MAX ( d.history_id )\n                    FROM v4_3_configuration_history_hosts_interfaces AS d\n                    GROUP BY d.host_interface_id\n                )\n                -- Here we get or remove deleted entities according to what the user chose\n                -- in the \"show_deleted\" parameter.\n                AND\n                    CASE\n                      WHEN '$show_deleted'='Yes'\n                      THEN 1=1\n                      WHEN '$show_deleted'='No'\n                      THEN delete_date isnull\n                    END\n            GROUP BY c.host_interface_id\n            ORDER BY\n                AVG (\n                    COALESCE ( b.receive_rate_percent, 0 )\n                ) +\n                AVG (\n                    COALESCE ( b.transmit_rate_percent, 0 )\n                ) DESC\n            LIMIT 5\n        )\n        -- Here we get or remove deleted entities according to what the user chose\n        -- in the \"show_deleted\" parameter.\n        AND\n            CASE\n              WHEN '$show_deleted'='Yes'\n              THEN 1=1\n              WHEN '$show_deleted'='No'\n              THEN delete_date isnull\n            END\n    GROUP BY\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        interface_name,\n        statistics.history_datetime\n) AS a\nGROUP BY\n    a.time,\n    interface_name,\n    Rx_rate,\n    Tx_rate\nORDER BY a.time"
    }
   ]
  },
  {
   "title": "Average Number of Virtual Machines and Peaks (Over Time) (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2A - This query returns the hourly hosts\n-- Active VMs Counts over time\n\nSELECT DISTINCT\n    $__time(a.time),\n    CAST ( VMS AS int ) AS \"Avg. Number of Vitual Machines\",\n    CAST ( VMS_Peak AS int ) AS \"Avg. Peaks of Number of Vitual Machines\"\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS,\n        SUM (\n            COALESCE (\n                max_active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS_Peak\n    -- If \"Period\" equals to \"Daily\" then \"table_name\" parameter\n    -- equals to \"hourly\" else \"daily\"\n    FROM\n        (\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_hourly\n             UNION\n             SELECT * FROM v4_3_statistics_hosts_resources_usage_daily\n        ) AS hourly_daily\n    WHERE\n        -- Here we filter by active hosts only\n        hourly_daily.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND hourly_daily.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    a.time,\n    VMS,\n    VMS_Peak\nORDER BY\n    a.time"
    }
   ]
  }
 ]
}