{
 "title": "Single Host Resource Usage Dashboard",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name AS __text , datacenter_id AS __value FROM v4_3_configuration_history_datacenters "
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT cluster_name AS __text, cluster_id AS __value FROM v4_3_configuration_history_clusters WHERE datacenter_id IN  ('$datacenter_id')"
   },
   {
    "name": "host_id",
    "label": "Host",
    "query": "SELECT DISTINCT host_name AS __text , host_id AS __value FROM v4_3_configuration_history_hosts WHERE cluster_id IN ('$cluster_id')"
   },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" }
  ]
 },
 "panels": [
  {
   "title": "Number of Virtual Machine By hour of Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Single Host Resource Usage - Average Number of Virtual Machine (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hourly hosts\n-- Max and Average Active VMs Counts\n\nSELECT DISTINCT\n    now() AS time,\n    to_char(time, 'HH24:00') AS hour_num,\n    AVG ( VMS ) AS \"Avg. Number of VMs\"\n--    AVG ( VMS_Peak ) AS \"Avg. VMs Peak\"\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS,\n        SUM (\n            COALESCE (\n                max_active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00')  ASC\n"
    }
   ]
  },
  {
   "title": "Single Host Resource Usage - Number of Virtual Machines Peaks  (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hourly hosts\n-- Max and Average Active VMs Counts\n\nSELECT DISTINCT\n    now() AS time,\n    to_char(time, 'HH24:00') AS hour_num,\n--    AVG ( VMS ) AS \"Avg. Number of VMs\",\n    AVG ( VMS_Peak ) AS \"Avg. VMs Peak\"\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS,\n        SUM (\n            COALESCE (\n                max_active_vms,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS VMS_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00')  ASC\n"
    }
   ]
  },
  { "title": "Host CPU Usage By hour of Day", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Single Host Resource Usage - Average CPU Usage (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hourly hosts\n-- Max and Average CPU Usage Peaks\n\nSELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day (HOUR) as a number.\n    to_char(time, 'HH24:00') AS hour_num,\n    AVG ( CPU_Usage ) AS CPU_Usage\n--    AVG ( CPU_Peak ) AS CPU_Peak\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                cpu_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Usage,\n        SUM (\n            COALESCE (\n                max_cpu_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00') ASC"
    }
   ]
  },
  {
   "title": "Single Host Resource Usage - Average CPU Usage Peaks (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns the hourly hosts\n-- Max and Average CPU Usage Peaks\n\nSELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day (HOUR) as a number.\n    to_char(time, 'HH24:00') AS hour_num,\n--    AVG ( CPU_Usage ) AS CPU_Usage,\n    AVG ( CPU_Peak ) AS CPU_Peak\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                cpu_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Usage,\n        SUM (\n            COALESCE (\n                max_cpu_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS CPU_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ($host_id)\n        AND history_datetime >= $__timeFrom()\n        AND history_datetime < $__timeTo()\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00') ASC"
    }
   ]
  },
  {
   "title": "Host Memory Usage By hour of Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Single Host Resource Usage - Average Memory Usage (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day ( HOUR ) AS a number.\n    to_char(time, 'HH24:00') AS hour_num,\n    AVG ( MEM_Usage ) AS \"Memory Usage\"\n--    AVG ( MEM_Peak ) AS \"Memory Usage Peaks\"\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                memory_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Usage,\n        SUM (\n            COALESCE (\n                max_memory_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n        AND history_datetime >= '2020-04-27T00:37:20.175Z'\n        AND history_datetime < '2020-05-04T09:55:10.369Z'\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n        to_char(time, 'HH24:00')\nORDER BY\n        to_char(time, 'HH24:00') ASC"
    }
   ]
  },
  {
   "title": "Single Host Resource Usage - Memory Usage Peaks (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day ( HOUR ) AS a number.\n    to_char(time, 'HH24:00') AS hour_num,\n--    AVG ( MEM_Usage ) AS \"Memory Usage\",\n    AVG ( MEM_Peak ) AS \"Memory Usage Peaks\"\nFROM (\n    -- Here we get the hosts Max and Average CPU Usage Peaks\n    SELECT\n        history_datetime AS time,\n        SUM (\n            COALESCE (\n                memory_usage_percent,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Usage,\n        SUM (\n            COALESCE (\n                max_memory_usage,\n                0\n            ) *\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) /\n        SUM (\n            COALESCE (\n                minutes_in_status,\n                0\n            )\n        ) AS MEM_Peak\n    FROM v4_3_statistics_hosts_resources_usage_hourly\n    WHERE\n        -- Here we filter by active hosts only\n        v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n        -- Here we filter by the host chosen by the user\n        AND v4_3_statistics_hosts_resources_usage_hourly.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n        AND history_datetime >= '2020-04-27T00:37:20.175Z'\n        AND history_datetime < '2020-05-04T09:55:10.369Z'\n    GROUP BY\n        history_datetime\n) AS a\nGROUP BY\n        to_char(time, 'HH24:00')\nORDER BY\n        to_char(time, 'HH24:00') ASC"
    }
   ]
  },
  {
   "title": "Host Interfatce Rx and Tx Usage By hour of Day",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Single Host Resource Usage - Interface Transmit Rate Usage (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- Ethernet Interface Tx and Rx Rates, by hour of day\n\nSELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day ( HOUR ) AS a number.\n    to_char(time, 'HH24:00')\n    AS hour_num,\n --   AVG ( Rx_rate ) AS Rx_rate,\n    AVG ( Tx_rate ) AS Tx_rate\nFROM (\n    SELECT\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        CASE\n            WHEN delete_date IS NULL\n                THEN\n                    v4_3_configuration_history_hosts_interfaces.host_interface_name\n            ELSE\n                v4_3_configuration_history_hosts_interfaces.host_interface_name\n                ||\n                '*'\n        END AS interface_name,\n        statistics.history_datetime AS time,\n        AVG (\n            COALESCE ( receive_rate_percent, 0 )\n        ) AS Rx_rate,\n        AVG (\n            COALESCE ( transmit_rate_percent, 0 )\n        ) AS Tx_rate\n    FROM\n        v4_3_statistics_hosts_interfaces_resources_usage_hourly\n        AS statistics\n        INNER JOIN v4_3_configuration_history_hosts_interfaces\n            ON (\n                v4_3_configuration_history_hosts_interfaces.host_interface_id =\n                statistics.host_interface_id\n            )\n    WHERE\n        -- Here we filter by the host chosen by the user\n        v4_3_configuration_history_hosts_interfaces.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n        AND history_datetime >= '2020-04-25T06:40:36.491Z'\n        AND history_datetime < '2020-05-25T06:40:36.491Z'\n        AND v4_3_configuration_history_hosts_interfaces.history_id IN (\n            SELECT MAX ( a.history_id )\n            FROM v4_3_configuration_history_hosts_interfaces AS a\n            GROUP BY a.host_interface_id\n        )\n        AND v4_3_configuration_history_hosts_interfaces.host_interface_id IN (\n            SELECT c.host_interface_id\n            FROM v4_3_statistics_hosts_interfaces_resources_usage_hourly b\n                INNER JOIN v4_3_configuration_history_hosts_interfaces c\n                    ON (\n                        c.host_interface_id = b.host_interface_id\n                    )\n                INNER JOIN v4_3_statistics_hosts_resources_usage_hourly\n                    ON (\n                        v4_3_statistics_hosts_resources_usage_hourly.history_datetime =\n                        b.history_datetime AND\n                        v4_3_statistics_hosts_resources_usage_hourly.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n                    )\n            WHERE\n                -- Here we filter by active hosts only\n                v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n                AND c.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n                AND b.history_datetime >= '2020-04-25T06:40:36.491Z'\n                AND b.history_datetime < '2020-05-25T06:40:36.491Z'\n                AND c.history_id IN (\n                    SELECT MAX ( d.history_id )\n                    FROM v4_3_configuration_history_hosts_interfaces AS d\n                    GROUP BY d.host_interface_id\n                )\n                -- Here we get or remove deleted VM devices according to what the user chose\n                -- in the \"show_deleted\" parameter\n                AND\n                  CASE\n                    WHEN 'No'='Yes'\n                      THEN 1=1\n                    WHEN 'No'='No'\n                      THEN delete_date isnull\n                  END\n            GROUP BY c.host_interface_id\n            ORDER BY\n                AVG (\n                    COALESCE ( b.receive_rate_percent, 0 )\n                ) +\n                AVG (\n                    COALESCE ( b.transmit_rate_percent, 0 )\n                ) DESC\n            LIMIT 3\n        )\n        -- Here we get or remove deleted VM devices according to what the user chose\n        -- in the \"show_deleted\" parameter\n        AND\n          CASE\n            WHEN 'No'='Yes'\n              THEN 1=1\n            WHEN 'No'='No'\n              THEN delete_date isnull\n          END\n    GROUP BY\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        interface_name,\n        statistics.history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00')"
    }
   ]
  },
  {
   "title": "Single Host Resource Usage - Interface Receive Usage Percent (BR2A)",
   "type": "graph",
   "description": "This report contains charts displaying resources usage measurements (Number of Virtual Machines, CPU, Memory, Network Tx/Rx) for a selected host over the selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "-- BR2C - This query returns top 3 busiest\n-- Ethernet Interface Tx and Rx Rates, by hour of day\n\nSELECT DISTINCT\n    now() AS time,\n    -- Here we get the hour of day ( HOUR ) AS a number.\n    to_char(time, 'HH24:00')\n    AS hour_num,\n    AVG ( Rx_rate ) AS Rx_rate\n--    AVG ( Tx_rate ) AS Tx_rate\nFROM (\n    SELECT\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        CASE\n            WHEN delete_date IS NULL\n                THEN\n                    v4_3_configuration_history_hosts_interfaces.host_interface_name\n            ELSE\n                v4_3_configuration_history_hosts_interfaces.host_interface_name\n                ||\n                '*'\n        END AS interface_name,\n        statistics.history_datetime AS time,\n        AVG (\n            COALESCE ( receive_rate_percent, 0 )\n        ) AS Rx_rate,\n        AVG (\n            COALESCE ( transmit_rate_percent, 0 )\n        ) AS Tx_rate\n    FROM\n        v4_3_statistics_hosts_interfaces_resources_usage_hourly\n        AS statistics\n        INNER JOIN v4_3_configuration_history_hosts_interfaces\n            ON (\n                v4_3_configuration_history_hosts_interfaces.host_interface_id =\n                statistics.host_interface_id\n            )\n    WHERE\n        -- Here we filter by the host chosen by the user\n        v4_3_configuration_history_hosts_interfaces.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n        AND history_datetime >= '2020-04-25T06:40:36.491Z'\n        AND history_datetime < '2020-05-25T06:40:36.491Z'\n        AND v4_3_configuration_history_hosts_interfaces.history_id IN (\n            SELECT MAX ( a.history_id )\n            FROM v4_3_configuration_history_hosts_interfaces AS a\n            GROUP BY a.host_interface_id\n        )\n        AND v4_3_configuration_history_hosts_interfaces.host_interface_id IN (\n            SELECT c.host_interface_id\n            FROM v4_3_statistics_hosts_interfaces_resources_usage_hourly b\n                INNER JOIN v4_3_configuration_history_hosts_interfaces c\n                    ON (\n                        c.host_interface_id = b.host_interface_id\n                    )\n                INNER JOIN v4_3_statistics_hosts_resources_usage_hourly\n                    ON (\n                        v4_3_statistics_hosts_resources_usage_hourly.history_datetime =\n                        b.history_datetime AND\n                        v4_3_statistics_hosts_resources_usage_hourly.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n                    )\n            WHERE\n                -- Here we filter by active hosts only\n                v4_3_statistics_hosts_resources_usage_hourly.host_status = 1\n                AND c.host_id in ('cf46710e-e0ba-481e-8ef3-8302f06debde','366adc66-ad57-4994-8257-1a50870a8a3a','1ff0515e-fcc5-48b6-889a-6ea0b039ce61','1e111b5e-4c53-44ab-ba26-9999fafa967f','e1b0c668-f452-46ff-89f5-038e7c0e9d7b')\n                AND b.history_datetime >= '2020-04-25T06:40:36.491Z'\n                AND b.history_datetime < '2020-05-25T06:40:36.491Z'\n                AND c.history_id IN (\n                    SELECT MAX ( d.history_id )\n                    FROM v4_3_configuration_history_hosts_interfaces AS d\n                    GROUP BY d.host_interface_id\n                )\n                -- Here we get or remove deleted VM devices according to what the user chose\n                -- in the \"show_deleted\" parameter\n                AND\n                  CASE\n                    WHEN 'No'='Yes'\n                      THEN 1=1\n                    WHEN 'No'='No'\n                      THEN delete_date isnull\n                  END\n            GROUP BY c.host_interface_id\n            ORDER BY\n                AVG (\n                    COALESCE ( b.receive_rate_percent, 0 )\n                ) +\n                AVG (\n                    COALESCE ( b.transmit_rate_percent, 0 )\n                ) DESC\n            LIMIT 3\n        )\n        -- Here we get or remove deleted VM devices according to what the user chose\n        -- in the \"show_deleted\" parameter\n        AND\n          CASE\n            WHEN 'No'='Yes'\n              THEN 1=1\n            WHEN 'No'='No'\n              THEN delete_date isnull\n          END\n    GROUP BY\n        v4_3_configuration_history_hosts_interfaces.host_interface_id,\n        interface_name,\n        statistics.history_datetime\n) AS a\nGROUP BY\n    to_char(time, 'HH24:00')\nORDER BY\n    to_char(time, 'HH24:00')"
    }
   ]
  }
 ]
}