{
 "title": "Virtual Machines Trend Dashboard",
 "description": "The virtual machines trend dashboard displaying resources usage measurements over time - Disk I/O rates, CPU, memory, and network Tx/Rx",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name AS __text , datacenter_id AS __value FROM v4_3_latest_configuration_datacenters"
   },
   {
    "name": "cluster_id",
    "label": "Cluster",
    "query": "SELECT DISTINCT cluster_name AS __text, cluster_id AS __value FROM v4_3_latest_configuration_clusters WHERE datacenter_id IN ('$datacenter_id')"
   },
   {
    "name": "vm_id",
    "label": "Virtual Machine",
    "query": "SELECT DISTINCT vm_name AS __text , vm_id AS __value FROM v4_3_configuration_history_vms WHERE cluster_id IN ('$cluster_id')"
   },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "\n###### This dashboard displays resource usage (CPU, memory, network Tx/Rx, disk I/O) for a selected virtual machine over a selected period.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Disk I/O Rates (over time) (BR10A)",
   "type": "graph",
   "description": "This report displays average disk read and write rates for a selected virtual machine over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10A - This query returns the\n-- VMs Disk Read_Rate, Write_Rate Usage\n-- over time.\n\nSELECT DISTINCT\n    $__time(all_sub_queries.time),\n    COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' ) AS disk_name,\n    AVG ( Read_Rate ) AS \"Read Rate\",\n    AVG ( Write_Rate ) AS \"Write Rate\"\nFROM \n    (\n        SELECT\n            CASE\n                WHEN delete_date IS NULL\n                    THEN vm_disk_name\n                ELSE vm_disk_name\n            ||\n            '*'\n            END AS disk_name,\n            history_datetime AS Time,\n            MAX ( ROUND ( CAST ( COALESCE ( read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric / ( 1024 * 1024 ), 1 ) ) AS Read_Rate,\n            MAX ( ROUND ( CAST ( COALESCE ( write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric / ( 1024 * 1024 ), 1 ) ) AS Write_Rate\n        FROM \n            (\n                SELECT * FROM v4_3_statistics_vms_disks_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_disks_resources_usage_daily\n            ) AS statistics\n            INNER JOIN v4_3_configuration_history_vms_disks\n                ON \n                    (\n                        v4_3_configuration_history_vms_disks.vm_disk_id =\n                        statistics.vm_disk_id\n                    )\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we filter by the latest vms_disks  configuration\n            AND v4_3_configuration_history_vms_disks.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_vms_disks AS a\n                        GROUP BY a.vm_disk_id\n                    )\n            AND v4_3_configuration_history_vms_disks.vm_disk_id \n                IN \n                    (\n                        SELECT c.vm_disk_id\n                        FROM \n                        (\n                            SELECT * FROM v4_3_statistics_vms_disks_resources_usage_hourly \n                            UNION\n                            SELECT * FROM v4_3_statistics_vms_disks_resources_usage_daily\n                        ) AS b\n                        INNER JOIN v4_3_configuration_history_vms_disks AS c\n                            ON \n                                (\n                                    c.vm_disk_id = \n                                    b.vm_disk_id\n                                )\n                        WHERE\n                            -- Here we filter by active vms disks only\n                            b.vm_disk_status = 1\n                            AND c.vm_disk_id \n                                IN \n                                    (\n                                        SELECT device_id\n                                        FROM \n                                            v4_3_configuration_history_vms_devices\n                                            INNER JOIN \n                                            (\n                                                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                                                UNION\n                                                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n                                            ) AS hourly_daily\n                                                ON\n\n                                                    (\n                                                        hourly_daily.vm_configuration_version =\n                                                        v4_3_configuration_history_vms_devices.vm_configuration_version\n                                                    )\n                                        WHERE\n                                            -- Here we filter by active vms only\n                                            hourly_daily.vm_status = 1\n                                            -- Here we filter by the vm chosen by the user\n                                            AND v4_3_configuration_history_vms_devices.vm_id IN ($vm_id)\n                                            AND create_date < $__timeTo()\n                                            AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                            -- Here we get the latest vm_devices configuration\n                                            AND v4_3_configuration_history_vms_devices.history_id \n                                                IN \n                                                    (\n                                                        SELECT MAX ( a.history_id )\n                                                        FROM v4_3_configuration_history_vms_devices a\n                                                        GROUP BY a.vm_id, a.device_id\n                                                    )\n                                            -- Here we get or remove deleted VM devices according to what the user chose\n                                            -- in the \"show_deleted\" parameter.\n                                            AND\n                                                CASE\n                                                    WHEN '$show_deleted'='Yes'\n                                                        THEN 1=1\n                                                    WHEN '$show_deleted'='No'\n                                                        THEN delete_date isnull\n                                                END\n                                    )\n                            AND history_datetime >= $__timeFrom()\n                            AND history_datetime < $__timeTo()\n                            -- Here we get the latest vm_disks configuration\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM  v4_3_configuration_history_vms_disks AS d\n                                        GROUP BY d.vm_disk_id\n                                    )\n                            -- Here we get or remove deleted VM disks according to what the user chose\n                            -- in the \"show_deleted\" parameter.\n                            AND\n                                CASE\n                                    WHEN '$show_deleted'='Yes'\n                                        THEN 1=1\n                                    WHEN '$show_deleted'='No'\n                                        THEN delete_date isnull\n                                END\n                        GROUP BY c.vm_disk_id\n                        -- Here we sort by the disks that have the max read and write rate.\n                        ORDER BY \n                            MAX ( ROUND ( CAST ( COALESCE ( b.read_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) +\n                            MAX ( ROUND ( CAST ( COALESCE ( b.write_rate_bytes_per_second, 0 ) AS FLOAT ) :: numeric, 1 ) ) \n                            DESC\n                        LIMIT 5\n                    )\n            -- Here we get or remove deleted entities according to what the user chose\n            -- in the \"show_deleted\" parameter.\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN delete_date isnull\n                END\n        GROUP BY\n        statistics.vm_disk_id,\n        disk_name, history_datetime\n    ) AS all_sub_queries\nGROUP BY all_sub_queries.time, disk_name\nORDER BY\n    all_sub_queries.time,\n    COALESCE ( disk_name, MAX ( disk_name ) over ( partition BY 1 ), '' )"
    }
   ]
  },
  {
   "title": "Top 3 Most Utilized Network Interfaces Tx and Rx Rates (over time) (BR10A)",
   "type": "graph",
   "description": "This report displays for the top 3 most utilized network interfaces the average transmit and receive rates for a selected virtual machine over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10A - This query returns the\n--  VMs Ethernet Interface Tx and Rx Rates\n-- over time.\n\nSELECT DISTINCT\n    $__time(all_sub_queries.time),\n    COALESCE ( interface_name, MAX ( interface_name ) over ( partition BY 1 ), '' ) AS interface_name,\n    AVG ( Rx_rate ) AS \"Rx. Rate\",\n    AVG ( Tx_rate ) AS \"Tx. Rate\"\nFROM \n    (\n        SELECT v4_3_configuration_history_vms_interfaces.vm_interface_id,\n            CASE\n                WHEN delete_date IS NULL\n                    THEN v4_3_configuration_history_vms_interfaces.vm_interface_name\n                ELSE v4_3_configuration_history_vms_interfaces.vm_interface_name\n            ||\n            '*'\n            END AS interface_name,\n            history_datetime AS time,\n            AVG ( COALESCE ( receive_rate_percent, 0 ) ) AS Rx_rate,\n            AVG ( COALESCE ( transmit_rate_percent, 0 ) ) AS Tx_rate\n        FROM \n            (    \n                SELECT * FROM v4_3_statistics_vms_interfaces_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_interfaces_resources_usage_daily\n            ) AS statistics\n            INNER JOIN v4_3_configuration_history_vms_interfaces\n            ON \n                (\n                    v4_3_configuration_history_vms_interfaces.vm_interface_id =\n                    statistics.vm_interface_id\n                )\n        WHERE \n            history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest vm_interfaces configuration\n            AND v4_3_configuration_history_vms_interfaces.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_vms_interfaces AS a\n                        GROUP BY a.vm_interface_id\n                    )\n            -- Here we get or remove deleted vm_interfaces according to what the user chose\n            -- in the \"show_deleted\" parameter.\n            AND\n                CASE\n                    WHEN '$show_deleted'='Yes'\n                        THEN 1=1\n                    WHEN '$show_deleted'='No'\n                        THEN delete_date isnull\n                END\n            AND v4_3_configuration_history_vms_interfaces.vm_interface_id \n                IN \n                    (\n                        SELECT c.vm_interface_id\n                        FROM     \n                            (\n                                SELECT * FROM v4_3_statistics_vms_interfaces_resources_usage_hourly\n                                UNION\n                                SELECT * FROM v4_3_statistics_vms_interfaces_resources_usage_daily\n                            ) AS b\n                            INNER JOIN v4_3_configuration_history_vms_interfaces AS c\n                                ON \n                                    (\n                                        c.vm_interface_id = \n                                        b.vm_interface_id\n                                    )\n                            INNER JOIN \n                            (\n                                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly \n                                UNION\n                                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n                            ) AS d\n                                ON \n                                    (\n                                        d.vm_configuration_version =\n                                        c.vm_configuration_version\n                                        AND d.history_datetime =\n                                        b.history_datetime\n                                    )\n                        WHERE\n                            -- Here we filter by active vms only\n                            d.vm_status = 1\n                            -- Here we filter by the VM chosen by the user\n                            AND c.vm_interface_id \n                                IN \n                                    (\n                                        SELECT device_id\n                                        FROM v4_3_configuration_history_vms_devices\n                                        WHERE \n                                            vm_id IN ($vm_id)\n                                            AND create_date < $__timeTo()\n                                            AND ( delete_date > $__timeFrom() OR delete_date IS NULL )\n                                            -- Here we get the latest vm_devices configuration\n                                            AND history_id \n                                                IN \n                                                    (\n                                                        SELECT MAX ( a.history_id )\n                                                        FROM v4_3_configuration_history_vms_devices AS a\n                                                        GROUP BY a.vm_id, a.device_id\n                                                    )\n                                            -- Here we get or remove deleted VMs according to what the user chose\n                                            -- in the \"show_deleted\" parameter.\n                                            AND\n                                                CASE\n                                                    WHEN '$show_deleted'='Yes'\n                                                        THEN 1=1\n                                                    WHEN '$show_deleted'='No'\n                                                        THEN delete_date isnull\n                                                END\n                                    )\n                            AND b.history_datetime >= $__timeFrom()\n                            AND b.history_datetime < $__timeTo()\n                            AND c.history_id \n                                IN \n                                    (\n                                        SELECT MAX ( d.history_id )\n                                        FROM v4_3_configuration_history_vms_interfaces AS d\n                                        GROUP BY d.vm_interface_id\n                                    )\n                            -- Here we get or remove deleted vm_interfaces according to what the user chose\n                            -- in the \"show_deleted\" parameter.\n                            AND\n                                CASE\n                                    WHEN '$show_deleted'='Yes'\n                                        THEN 1=1\n                                    WHEN '$show_deleted'='No'\n                                        THEN delete_date isnull\n                                END\n                        GROUP BY c.vm_interface_id\n                        ORDER BY\n                            AVG ( COALESCE ( b.receive_rate_percent, 0 ) ) +\n                            AVG ( COALESCE ( b.transmit_rate_percent, 0 ) ) \n                            DESC\n                        LIMIT 3\n                    )\n        GROUP BY\n            v4_3_configuration_history_vms_interfaces.vm_interface_id,\n            interface_name,\n            history_datetime\n    ) AS all_sub_queries\nGROUP BY all_sub_queries.time, interface_name\nORDER BY all_sub_queries.time ASC"
    }
   ]
  },
  {
   "title": "Average Memory Usage and Peaks (over time) (BR10A)",
   "type": "graph",
   "description": "This report displays average memory usage and peaks for a selected virtual machine over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10A - This query returns the\n-- VMs max and Average memory usage peaks\n-- over time.\n\nSELECT\n    $__time(time),\n    MEM_Usage AS \"Memory Usage\",\n    MEM_Peak AS \"Memory Peak\"\nFROM \n    (\n        -- VMs Max and Average MEMory Usage Peaks\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( memory_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Usage,\n            SUM ( COALESCE ( max_memory_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS MEM_Peak\n        FROM\n            ( \n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n        WHERE\n            -- Here we filter by active vms only\n            hourly_daily.vm_status = 1\n            -- Here we filter by the vm chosen by the user\n            AND hourly_daily.vm_id IN ($vm_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\nGROUP BY time, MEM_Usage, MEM_Peak\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average CPU Usage and Peaks (over time) (BR10A)",
   "type": "graph",
   "description": "This report displays average CPU usage and peaks for a selected virtual machine over a selected period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- BR10A - This query returns the\n-- VMs Max and Average CPU Usage Peaks\n-- over time.\n\nSELECT\n    $__time(time),\n    CPU_Usage AS \"CPU Usage\",\n    CPU_Peak AS \"CPU Peak\"\nFROM \n    (\n        -- Here we get the vms Max and Average CPU Usage Peaks\n        SELECT\n            history_datetime AS time,\n            SUM ( COALESCE ( cpu_usage_percent, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Usage,\n            SUM ( COALESCE ( max_cpu_usage, 0 ) * COALESCE ( minutes_in_status, 0 ) ) /\n            SUM ( COALESCE ( minutes_in_status, 0 ) ) AS CPU_Peak\n        FROM \n            (\n                SELECT * FROM v4_3_statistics_vms_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_vms_resources_usage_daily\n            ) AS hourly_daily\n        WHERE\n            -- Here we filter by active vms only\n            hourly_daily.vm_status = 1\n            -- Here we filter by the vm chosen by the user\n            AND hourly_daily.vm_id IN ($vm_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n        GROUP BY history_datetime\n    ) AS sub_query\nGROUP BY time, CPU_Usage, CPU_Peak\nORDER BY time"
    }
   ]
  }
 ]
}