{
 "title": "Storage Domains Inventory Dashboard",
 "description": "The storage domain inventory dashboard include storage domain inventory list and disk usage",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "datacenter_id",
    "label": "Data Center",
    "query": "SELECT DISTINCT datacenter_name AS __text , datacenter_id AS __value FROM v4_3_latest_configuration_datacenters"
   },
   {
    "name": "storage_id",
    "label": "Storage Domain",
    "query": "SELECT DISTINCT     CAST (         v4_3_configuration_history_storage_domains.storage_domain_id AS varchar     ) AS __value,     CASE         WHEN detach_date IS NULL             THEN storage_domain_name         ELSE             storage_domain_name             ||             ' ('             ||             'Detached on'             ||             ' '             ||             TO_CHAR (                 detach_date, 'YYYY-MM-DD'             )             ||             ')'     END AS __text FROM v4_3_configuration_history_storage_domains         INNER JOIN v4_3_map_history_datacenters_storage_domains             ON (                 v4_3_map_history_datacenters_storage_domains.storage_domain_id =                 v4_3_configuration_history_storage_domains.storage_domain_id                 AND v4_3_map_history_datacenters_storage_domains.datacenter_id =                 CAST ( '$datacenter_id' AS uuid )             ) WHERE v4_3_configuration_history_storage_domains.storage_domain_type IN ($storage_type )     AND v4_3_map_history_datacenters_storage_domains.history_id IN (         SELECT MAX ( a.history_id )         FROM v4_3_map_history_datacenters_storage_domains a         GROUP BY a.storage_domain_id, a.datacenter_id     )     AND v4_3_configuration_history_storage_domains.history_id IN (         SELECT MAX ( a.history_id )         FROM v4_3_configuration_history_storage_domains a         GROUP BY a.storage_domain_id     )     AND         CASE           WHEN '$show_deleted'='Yes'           THEN 1=1           WHEN '$show_deleted'='No'           THEN detach_date isnull         END     AND         CASE           WHEN '$show_deleted'='Yes'           THEN 1=1           WHEN '$show_deleted'='No'           THEN delete_date isnull         END ORDER BY     __text"
   },
   {
    "name": "storage_type",
    "label": "Storage Type",
    "query": "SELECT DISTINCT     enum_translator.value AS __text,     enum_translator.enum_key AS __value FROM enum_translator  WHERE     enum_translator.language_code = 'en_US'     AND enum_translator.enum_type ='STORAGE_DOMAIN_TYPE'"
   },
   { "name": "show_deleted", "label": "Show Deleted Entities?", "query": "No,Yes" }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "\n###### This dashboard include inventory list and disk usage for the selected storage domain.\n\n\n\n",
   "targets": [
    {
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  { "title": "Reports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Storage Domains Inventory (BR47)",
   "type": "table",
   "description": "This report displays a inventory list of all storage domains of the selected data center.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "--BR47 - This query returns for a specific datacenter, the storage domains list,\n-- along with their configuration details, available disk size, \n-- used disk size and total, up to an hour back.\n\n-- storage_domain_type and storage_type will be returned in localised session language.\nSELECT\n    storage_domain_name,\n    v4_3_configuration_history_storage_domains.storage_domain_id,\n    a.value AS storage_domain_type,\n    b.value AS storage_type,\n    available_disk_size_gb, \n    used_disk_size_gb,\n    ( available_disk_size_gb + used_disk_size_gb ) AS total_size,\n    create_date,\n    delete_date\nFROM \n    v4_3_configuration_history_storage_domains\n    INNER JOIN v4_3_map_history_datacenters_storage_domains\n        ON \n            (\n                v4_3_configuration_history_storage_domains.storage_domain_id =\n                v4_3_map_history_datacenters_storage_domains.storage_domain_id\n                -- Here we filter by the datacenter chosen by the user\n                AND v4_3_map_history_datacenters_storage_domains.datacenter_id =\n                    CAST ( '$datacenter_id' AS uuid )\n                -- Here we get the latest map\n                AND v4_3_map_history_datacenters_storage_domains.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM v4_3_map_history_datacenters_storage_domains a\n                            GROUP BY a.storage_domain_id, a.datacenter_id\n                        )\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS a\n        ON \n            (\n                storage_domain_type = a.enum_key\n                AND a.enum_type = 'STORAGE_DOMAIN_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT\n                enum_translator.enum_type,\n                enum_translator.enum_key,\n                enum_translator.value\n            FROM enum_translator\n            WHERE language_code = 'en_US'\n        ) AS b\n        ON \n            (\n                storage_type = b.enum_key\n                AND b.enum_type = 'STORAGE_TYPE'\n            )\n    LEFT OUTER JOIN \n        (\n            SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n            union\n            SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n        ) AS hourly_daily\n        ON \n            (\n                v4_3_configuration_history_storage_domains.storage_domain_id =\n                hourly_daily.storage_domain_id\n                AND hourly_daily.history_id \n                    IN \n                        (\n                            SELECT MAX ( a.history_id )\n                            FROM             \n                                (   \n                                    SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n                                    union\n                                    SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n                                ) AS a    \n                            GROUP BY a.storage_domain_id\n                        )\n            )\nWHERE\n    v4_3_configuration_history_storage_domains.storage_domain_id IN ($storage_id)\n    -- Here we filter by the storage type chosen by the user\n    -- If \"All\" storage types were chosen by the user then the\n    -- parameter \"P_Storage_Type\" equals to -1\n    AND storage_domain_type IN ($storage_type)\n    -- Here we get the storage domain latest configurations\n    AND v4_3_configuration_history_storage_domains.history_id \n        IN \n            (\n                SELECT MAX ( a.history_id )\n                FROM v4_3_configuration_history_storage_domains AS a\n                GROUP BY a.storage_domain_id\n            )\n    -- This will determine where deleted entities will be included in the report,\n    -- according to the user selection for \"show_deleted\" parameter\n    AND\n        CASE\n          WHEN '$show_deleted'='Yes'\n              THEN 1=1\n          WHEN '$show_deleted'='No'\n              THEN delete_date isnull\n        END\nORDER BY storage_domain_name"
    }
   ]
  },
  {
   "title": "Storage Domain Available Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays average available disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average available disk size per hour over the chosen period.\n\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    available_disk_size\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n            ) AS hourly_daily,\n            v4_3_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_3_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_3_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\nORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Used Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays average used disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the average used disk size per hour for the chosen period.\n\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n            ) AS hourly_daily,\n            v4_3_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_3_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_3_configuration_history_storage_domains.history_id \n                IN \n                    (\n                    SELECT MAX ( a.history_id )\n                    FROM v4_3_configuration_history_storage_domains a\n                    GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\nORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Total Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays used disk size versus available disk size ( total disk size ) for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the available disk size versus used disk size ( total disk size ), \n-- per hour for the chosen period.\n\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size AS \"( Used disk size )\",\n    available_disk_size AS \"( Available disk size )\"\n    --,( available_disk_size + used_disk_size ) AS \"( Total disk size )\"\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( available_disk_size_gb ) AS available_disk_size,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n            ) AS hourly_daily,\n            v4_3_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_3_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_3_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\n    ORDER BY sub_query.history_datetime"
    }
   ]
  },
  {
   "title": "Storage Domain Total Used Size (over time) (BR21)",
   "type": "graph",
   "description": "This report displays total used disk size for the selected data center and storage domain over a selected period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "rawSql": "-- BR21 - This query returns for a specific storage domain\n-- the total used disk size per hour for the chosen period.\n\nSELECT DISTINCT\n    $__time(sub_query.history_datetime),\n    COALESCE \n        (\n            storage_domain_name,\n            MAX ( storage_domain_name ) over ( partition BY 1 ),\n            ''\n        ) AS storage_domain_name,\n    used_disk_size\nFROM \n    (\n        SELECT\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime,\n            AVG ( used_disk_size_gb ) AS used_disk_size\n        FROM\n            (\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_hourly\n                UNION\n                SELECT * FROM v4_3_statistics_storage_domains_resources_usage_daily\n            ) AS hourly_daily,\n            v4_3_configuration_history_storage_domains\n        WHERE\n            -- Here we join the the storage domain configurations table with the statistics table\n            v4_3_configuration_history_storage_domains.storage_domain_id =\n            hourly_daily.storage_domain_id\n            -- Here we filter by the storage domain chosen by the user\n            AND hourly_daily.storage_domain_id IN ($storage_id)\n            AND history_datetime >= $__timeFrom()\n            AND history_datetime < $__timeTo()\n            -- Here we get the latest storage domain configurations\n            AND v4_3_configuration_history_storage_domains.history_id \n                IN \n                    (\n                        SELECT MAX ( a.history_id )\n                        FROM v4_3_configuration_history_storage_domains a\n                        GROUP BY a.storage_domain_id\n                    )\n        GROUP BY\n            v4_3_configuration_history_storage_domains.storage_domain_name,\n            history_datetime\n    ) AS sub_query\nORDER BY sub_query.history_datetime"
    }
   ]
  }
 ]
}