SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\660E\306E\30B9\30C6\30FC\30BF\30B9' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast(U&'Unbekannter Status' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast(U&'Unknown Status' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast(U&'Estatus desconocido' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast(U&'Statut inconnu' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Status desconhecidos' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\77E5\7684\72B6\6001' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'In Betrieb' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Up' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Funcionando' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Actif' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\7A3C\50CD\4E2D' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Ativo' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E0A\7EBF\7684' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Wartung' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Maintenance' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Mantenimiento' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Maintenance' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\30E1\30F3\30C6\30CA\30F3\30B9' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Manuten\00E7\00E3o' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7EF4\62A4' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Problematisch' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Problematic' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Probl\00E9matic' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\554F\984C\3042\308A' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('DATACENTER_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6709\95EE\9898\7684' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('de' as varchar(40)),cast(U&'Benutzer' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('en_US' as varchar(40)),cast(U&'User' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('es' as varchar(40)),cast(U&'Usuario' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('fr' as varchar(40)),cast(U&'Utililisateur' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('ja' as varchar(40)),cast(U&'\30E6\30FC\30B6\30FC' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Usu\00E1rio' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(15 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7528\6237' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('de' as varchar(40)),cast(U&'Benutzergruppe' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('en_US' as varchar(40)),cast(U&'User Group' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('es' as varchar(40)),cast(U&'Grupo de usuarios' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('fr' as varchar(40)),cast(U&'Groupe d''utilisateurs' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('ja' as varchar(40)),cast(U&'\30E6\30FC\30B6\30FC\30B0\30EB\30FC\30D7' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Grupo de Usu\00E1rio' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(17 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7528\6237\7EC4' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('de' as varchar(40)),cast(U&'Marke' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('en_US' as varchar(40)),cast(U&'Tag' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('es' as varchar(40)),cast(U&'Etiqueta' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('fr' as varchar(40)),cast(U&'Balise' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('ja' as varchar(40)),cast(U&'\30BF\30B0' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Tag' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(18 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6807\7B7E' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'VM' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\4EEE\60F3\30DE\30B7\30F3' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\865A\62DF\673A' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'H\00F4te' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\30DB\30B9\30C8' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Host' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E3B\673A' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast(U&'VM-Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast(U&'VM Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast(U&'Pool MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast(U&'VM Pool' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast(U&'\4EEE\60F3\30DE\30B7\30F3\30D7\30FC\30EB' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Pool da MV' as text));
SELECT update_enum_translator(cast('ENTITY_TYPE' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\865A\62DF\673A\6C60' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast(U&'Unbekannter Status' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast(U&'Unknown Status' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast(U&'Estatus desconocido' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast(U&'Statut inconnu' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\660E\306E\30B9\30C6\30FC\30BF\30B9' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Status desconhecidos' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\77E5\7684\72B6\6001' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'In Betrieb' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Up' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Funcionando' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Actif' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\7A3C\50CD\4E2D' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Ativo' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E0A\7EBF\7684' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Wartung' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Maintenance' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Mantenimiento' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Maintenance' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\30E1\30F3\30C6\30CA\30F3\30B9' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Manuten\00E7\00E3o' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7EF4\62A4' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Problematisch' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Problematic' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Probl\00E9matic' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\554F\984C\3042\308A' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('HOST_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6709\95EE\9898\7684' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('HOST_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEV' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'rtl8139-pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'rtl8139' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'e1000' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('NIC_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'pv' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Unbekannt' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Unknown' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Desconocido' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Inconnu' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\660E' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desconhecido' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\77E5\7684' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows XP' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('de' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('es' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(10 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 2003 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('de' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('es' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(11 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 7' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('de' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('es' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(12 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 7 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(13 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 5 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(14 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 4 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(15 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 3 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('de' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('es' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(16 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 2008 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('de' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('es' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(17 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 2008R2 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(18 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(19 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 6 x64' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 2003' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Windows 2008' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast(U&'Andere Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast(U&'Other Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast(U&'Otro Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast(U&'Autre Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast(U&'\305D\306E\4ED6\306E Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Outro Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5176\4ED6 Linux' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('de' as varchar(40)),cast(U&'Sonstige' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('en_US' as varchar(40)),cast(U&'Other' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('es' as varchar(40)),cast(U&'Otros' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('fr' as varchar(40)),cast(U&'Autre' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('ja' as varchar(40)),cast(U&'\305D\306E\4ED6' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Outro' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(6 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5176\4ED6\7684' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(7 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 5' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(8 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 4' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('de' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('en_US' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('es' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('fr' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('ja' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('pt_BR' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('OS_TYPE' as varchar(40)),cast(9 as smallint),cast('zh_CN' as varchar(40)),cast(U&'RHEL 3' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Alle' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'All' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Todos' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Tous' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\3059\3079\3066' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Todos' as text));
SELECT update_enum_translator(cast('REPORTS_ALL' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5168\90E8' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Abgeh\00E4ngt von ' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Detached on' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Separado el' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'D\00E9tach\00E9 sur' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30BF\30C3\30C1\3055\308C\305F\65E5\4ED8' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desanexado no' as text));
SELECT update_enum_translator(cast('REPORTS_DETACHED_ON' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\9644\52A0\5728' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Keine verf\00FCgbar' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'None Available' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Ninguno disponible' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Aucunes Disponible' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30FC\30BF\304C\3042\308A\307E\305B\3093' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Nada Encontrado' as text));
SELECT update_enum_translator(cast('REPORTS_NONE_AVAILABLE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6CA1\6709\53EF\7528\7684' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'T\00E4glich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Daily' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Diariamente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Chaque jour' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\65E5\6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Di\00E1rio' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6309\65E5' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Monatlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Monthly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Mensualmente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Chaque mois' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\6708\6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Mensal' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6309\6708' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Viertelj\00E4hrlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Quarterly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Cada cuarto' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Tous les 3 mois' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\56DB\534A\671F' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Trimestral' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6309\5B63\5EA6' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'J\00E4hrlich' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Yearly' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Anualmente' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Chaque ann\00E9e' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\5E74\6B21' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Anual' as text));
SELECT update_enum_translator(cast('REPORTS_PERIOD' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6309\5E74\5EA6' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Entfernt auf ' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Removed on' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Borrado el' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Supprim\00E9 de' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\524A\9664\3055\308C\305F\65E5\4ED8' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Removido no' as text));
SELECT update_enum_translator(cast('REPORTS_REMOVED_ON' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5DF2\5220\9664' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Nein' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'No' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'No' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Non' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\3044\3044\3048' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'N\00E3o' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5426' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Ja' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Yes' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Si' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Oui' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\306F\3044' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Sim' as text));
SELECT update_enum_translator(cast('REPORTS_SHOW_DELETED' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\662F' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Getrennt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Unattached' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Separado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Non attach\00E9' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\672A\30A2\30BF\30C3\30C1' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desanexado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\9644\52A0\7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Aktiv' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Active' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Activo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Actif' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\30A2\30AF\30C6\30A3\30D6' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Ativar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6D3B\52A8\7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Inaktiv' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'InActive' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Inactivo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Inactif' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\975E\30A2\30AF\30C6\30A3\30D6' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Inativo' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E0D\6D3B\52A8\7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Gemischt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Mixed' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Mezclado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Mixte' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\6DF7\5728' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Mesclado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6DF7\5408\7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast(U&'Gesperrt' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast(U&'Locked' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast(U&'Bloqueado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast(U&'Verrouill\00E9' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast(U&'\30ED\30C3\30AF' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Bloqueado' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_STATUS' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\9501\4F4F\7684' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Daten (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Data (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Datos (Maestro)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Donn\00E9es (Master)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30FC\30BF (\30DE\30B9\30BF\30FC)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Dados (Mestre)' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6570\636E\FF08\4E3B\FF09' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Daten' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Data' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Datos' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Donn\00E9es' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30FC\30BF' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Dados' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6570\636E' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'ISO' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Exportar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Export' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\30A8\30AF\30B9\30DD\30FC\30C8' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Exportar' as text));
SELECT update_enum_translator(cast('STORAGE_DOMAIN_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5BFC\51FA' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Unbekannt' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Unknown' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Desconocido' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Inconnu' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\660E' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desconhecido' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\77E5\7684' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'NFS' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'FCP' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'iSCSI' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast(U&'Lokal' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast(U&'Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast(U&'Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast(U&'Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast(U&'\30ED\30FC\30AB\30EB' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Local' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('de' as varchar(40)),cast(U&'Alle' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('en_US' as varchar(40)),cast(U&'All' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('es' as varchar(40)),cast(U&'Todos' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('fr' as varchar(40)),cast(U&'Tous' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('ja' as varchar(40)),cast(U&'\3059\3079\3066' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Todos' as text));
SELECT update_enum_translator(cast('STORAGE_TYPE' as varchar(40)),cast(6 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\5168\90E8' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Aktiviert' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Enabled' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Habilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Activ\00E9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\6709\52B9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Habilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\542F\7528' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Inaktiv' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Disabled' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Inhabilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'D\00E9sactiv\00E9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\7121\52B9' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desabilitado' as text));
SELECT update_enum_translator(cast('USB_POLICY' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7981\7528' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Non assign\00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\672A\5272\308A\5F53\3066' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'N\00E3o determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\5206\914D\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast(U&'COW' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('de' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('en_US' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('es' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('fr' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('ja' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_FORMAT' as varchar(40)),cast(5 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Raw' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'IDE' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'SCSI' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_INTERFACE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'Virt IO' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Non assign\00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\672A\5272\308A\5F53\3066' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'N\00E3o Determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\5206\914D\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'OK' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Gesperrt' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Locked' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Bloqueado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Verrouill\00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\30ED\30C3\30AF' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Bloqueado' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\9501\4F4F\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Ung\00FCltig' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Invalid' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Inv\00E1lido' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Invalide' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\7121\52B9' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Inv\00E1lido' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\65E0\6548\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('de' as varchar(40)),cast(U&'Verboten' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('en_US' as varchar(40)),cast(U&'Illegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('es' as varchar(40)),cast(U&'Ilegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('fr' as varchar(40)),cast(U&'Ill\00E9gal(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\6B63' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Ilegal' as text));
SELECT update_enum_translator(cast('VM_DISK_STATUS' as varchar(40)),cast(4 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\975E\6CD5\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Unbestimmt' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Unassigned' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'No asignado' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Non assign\00E9(e)' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\672A\5272\308A\5F53\3066' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'N\00E3o determinado' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\5206\914D\7684' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'System' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'System' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Sistema' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Syst\00E8me' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\30B7\30B9\30C6\30E0' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Sistema' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\7CFB\7EDF' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Daten' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Data' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'Datos' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Donn\00E9es' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30FC\30BF' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Dados' as text));
SELECT update_enum_translator(cast('VM_DISK_TYPE' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6570\636E' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('de' as varchar(40)),cast(U&'Unbekannter Status' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('en_US' as varchar(40)),cast(U&'Unknown Status' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('es' as varchar(40)),cast(U&'Estatus desconocido' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('fr' as varchar(40)),cast(U&'Statut inconnu' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('ja' as varchar(40)),cast(U&'\4E0D\660E\306E\30B9\30C6\30FC\30BF\30B9' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Status Desconhecido' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(-1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\672A\77E5\7684\72B6\6001' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Au\00DFer Betrieb' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Down' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'No funciona' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Inactif' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\505C\6B62\4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Inativo' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E0B\7EBF\7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'In Betrieb' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Up' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Funcionando' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Actif' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\7A3C\50CD\4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Ativado' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\4E0A\7EBF\7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('de' as varchar(40)),cast(U&'Angehalten' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('en_US' as varchar(40)),cast(U&'Paused' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('es' as varchar(40)),cast(U&'En pausa' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('fr' as varchar(40)),cast(U&'Sur pause' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('ja' as varchar(40)),cast(U&'\4E00\6642\505C\6B62\4E2D' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Pausado' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(2 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6682\505C\7684' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('de' as varchar(40)),cast(U&'Problematisch' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('en_US' as varchar(40)),cast(U&'Problematic' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('es' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('fr' as varchar(40)),cast(U&'Probl\00E9matic' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('ja' as varchar(40)),cast(U&'\554F\984C\3042\308A' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Problem\00E1tico' as text));
SELECT update_enum_translator(cast('VM_STATUS' as varchar(40)),cast(3 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\6709\95EE\9898\7684' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('de' as varchar(40)),cast(U&'Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('en_US' as varchar(40)),cast(U&'Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('es' as varchar(40)),cast(U&'Escritorio' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('fr' as varchar(40)),cast(U&'Bureau' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('ja' as varchar(40)),cast(U&'\30C7\30B9\30AF\30C8\30C3\30D7' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Desktop' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(0 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\684C\9762' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('de' as varchar(40)),cast(U&'Server' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('en_US' as varchar(40)),cast(U&'Server' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('es' as varchar(40)),cast(U&'Servidor' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('fr' as varchar(40)),cast(U&'Serveur' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('ja' as varchar(40)),cast(U&'\30B5\30FC\30D0\30FC' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('pt_BR' as varchar(40)),cast(U&'Servidor' as text));
SELECT update_enum_translator(cast('VM_TYPE' as varchar(40)),cast(1 as smallint),cast('zh_CN' as varchar(40)),cast(U&'\670D\52A1\5668' as text));
