-- Change host interface rx/tx rate
select fn_db_change_column_type('host_interface_samples_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_samples_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_hourly_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_hourly_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_hourly_history', 'max_receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_hourly_history', 'max_transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_daily_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_daily_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_daily_history', 'max_receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('host_interface_daily_history', 'max_transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
-- Change vm interface rx/tx rate
select fn_db_change_column_type('vm_interface_samples_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_samples_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_hourly_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_hourly_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_hourly_history', 'max_receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_hourly_history', 'max_transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_daily_history', 'receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_daily_history', 'transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_daily_history', 'max_receive_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
select fn_db_change_column_type('vm_interface_daily_history', 'max_transmit_rate_percent', 'NUMERIC', 'NUMERIC(24, 4)');
-- Change host interface rx/tx drop
select fn_db_change_column_type('host_interface_samples_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_samples_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_hourly_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_hourly_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_daily_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_daily_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
-- Change vm interface rx/tx drop
select fn_db_change_column_type('vm_interface_samples_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_samples_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_hourly_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_hourly_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_daily_history', 'received_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_daily_history', 'transmitted_dropped_total_packets', 'NUMERIC', 'NUMERIC(20, 0)');
-- Change host interface rx/tx total
select fn_db_change_column_type('host_interface_samples_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_samples_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_hourly_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_hourly_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_daily_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('host_interface_daily_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');
-- Change vm interface rx/tx total
select fn_db_change_column_type('vm_interface_samples_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_samples_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_hourly_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_hourly_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_daily_history', 'received_total_byte', 'bigint', 'NUMERIC(20, 0)');
select fn_db_change_column_type('vm_interface_daily_history', 'transmitted_total_byte', 'bigint', 'NUMERIC(20, 0)');