name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: ovirt/checkout-action@main

    - name: Use cache for maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@main
      with:
        directory: ${{ env.ARTIFACTS_DIR}}
